#!/usr/bin/env bash

# Source: https://peter.bourgon.org/go-best-practices-2016/

set -o errexit
set -o nounset
set -o pipefail

if [ ! $(command -v golangci-lint) ]
then
	go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
fi

golangci-lint run --config=$GOPATH/src/github.com/corestoreio/pkg/.golangci.yml $@\
