#!/usr/bin/env bash

# Source: https://peter.bourgon.org/go-best-practices-2016/

set -o errexit
set -o nounset
set -o pipefail

if [ ! $(command -v gometalinter) ]
then
	go get github.com/alecthomas/gometalinter
	gometalinter --update --install
fi

megacheck -tags csall $@
gometalinter --no-config \
	--skip=internal \
	--exclude='error return value not checked.*(Close|Log|Print).*\(errcheck\)$' \
	--exclude='.*_test\.go:.*error return value not checked.*\(errcheck\)$' \
	--exclude='duplicate of.*_test.go.*\(dupl\)$' \
	--disable=aligncheck \
	--disable=gotype \
	--disable=megacheck \
	--cyclo-over=20 \
	--tests \
	--deadline=1m $@ | grep -v usr/local/go-master/libexec


