// +build easyjson

// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package null_test

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8d5c760DecodeGithubComCorestoreioPkgStorageNull(in *jlexer.Lexer, out *StringEmbedded) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "string_1":
			(out.String1).UnmarshalEasyJSON(in)
		case "string_2":
			(out.String2).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func easyjson8d5c760EncodeGithubComCorestoreioPkgStorageNull(out *jwriter.Writer, in StringEmbedded) {
	out.RawByte('{')
	first := true
	_ = first
	if (in.String1).IsDefined() {
		const prefix string = ",\"string_1\":"
		first = false
		out.RawString(prefix[1:])
		(in.String1).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"string_2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.String2).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StringEmbedded) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8d5c760EncodeGithubComCorestoreioPkgStorageNull(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StringEmbedded) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8d5c760EncodeGithubComCorestoreioPkgStorageNull(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StringEmbedded) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8d5c760DecodeGithubComCorestoreioPkgStorageNull(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StringEmbedded) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8d5c760DecodeGithubComCorestoreioPkgStorageNull(l, v)
}
