// Code generated by codegen. DO NOT EDIT.
package dmltestgenerated2

import (
	"testing"

	"github.com/corestoreio/pkg/util/assert"
	"github.com/corestoreio/pkg/util/pseudo"
)

func TestNewTablesNonDB(t *testing.T) {
	ps := pseudo.MustNewService(0, &pseudo.Options{Lang: "de", FloatMaxDecimals: 6})
	t.Run("CoreConfigData_Empty", func(t *testing.T) {
		e := new(CoreConfigData)
		assert.NoError(t, ps.FakeData(e))
		e.Empty()
		assert.Exactly(t, *e, CoreConfigData{})
	})
	t.Run("CoreConfigData_Copy", func(t *testing.T) {
		e := new(CoreConfigData)
		assert.NoError(t, ps.FakeData(e))
		e2 := e.Copy()
		assert.Exactly(t, e, e2)
		assert.NoError(t, ps.FakeData(e))
		assert.NotEqual(t, e, e2)
	})
	t.Run("SalesOrderStatusState_Empty", func(t *testing.T) {
		e := new(SalesOrderStatusState)
		assert.NoError(t, ps.FakeData(e))
		e.Empty()
		assert.Exactly(t, *e, SalesOrderStatusState{})
	})
	t.Run("SalesOrderStatusState_Copy", func(t *testing.T) {
		e := new(SalesOrderStatusState)
		assert.NoError(t, ps.FakeData(e))
		e2 := e.Copy()
		assert.Exactly(t, e, e2)
		assert.NoError(t, ps.FakeData(e))
		assert.NotEqual(t, e, e2)
	})
}
