// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dmltestgenerated

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated(in *jlexer.Lexer, out *DmlgenTypesCollection) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]*DmlgenTypes, 0, 8)
					} else {
						out.Data = []*DmlgenTypes{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *DmlgenTypes
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(DmlgenTypes)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Data = append(out.Data, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated(out *jwriter.Writer, in DmlgenTypesCollection) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v2, v3 := range in.Data {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DmlgenTypesCollection) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DmlgenTypesCollection) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DmlgenTypesCollection) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DmlgenTypesCollection) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated(l, v)
}
func easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated1(in *jlexer.Lexer, out *DmlgenTypes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int32(in.Int32())
		case "col_bigint_1":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColBigint1).UnmarshalJSON(data))
			}
		case "col_bigint_2":
			out.ColBigint2 = int64(in.Int64())
		case "col_bigint_3":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColBigint3).UnmarshalJSON(data))
			}
		case "col_bigint_4":
			out.ColBigint4 = uint64(in.Uint64())
		case "col_blob":
			if in.IsNull() {
				in.Skip()
				out.ColBlob = nil
			} else {
				out.ColBlob = in.Bytes()
			}
		case "col_date_1":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColDate1).UnmarshalJSON(data))
			}
		case "col_date_2":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColDate2).UnmarshalJSON(data))
			}
		case "col_datetime_1":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColDatetime1).UnmarshalJSON(data))
			}
		case "col_datetime_2":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColDatetime2).UnmarshalJSON(data))
			}
		case "col_decimal_10_1":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColDecimal101).UnmarshalJSON(data))
			}
		case "col_decimal_12_4":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColDecimal124).UnmarshalJSON(data))
			}
		case "price_12_4a":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Price124a).UnmarshalJSON(data))
			}
		case "price_12_4b":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Price124b).UnmarshalJSON(data))
			}
		case "col_decimal_12_3":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColDecimal123).UnmarshalJSON(data))
			}
		case "col_decimal_20_6":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColDecimal206).UnmarshalJSON(data))
			}
		case "col_decimal_24_12":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColDecimal2412).UnmarshalJSON(data))
			}
		case "col_int_1":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColInt1).UnmarshalJSON(data))
			}
		case "col_int_2":
			out.ColInt2 = int32(in.Int32())
		case "col_int_3":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColInt3).UnmarshalJSON(data))
			}
		case "col_int_4":
			out.ColInt4 = uint32(in.Uint32())
		case "col_longtext_1":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColLongtext1).UnmarshalJSON(data))
			}
		case "col_longtext_2":
			out.ColLongtext2 = string(in.String())
		case "col_mediumblob":
			if in.IsNull() {
				in.Skip()
				out.ColMediumblob = nil
			} else {
				out.ColMediumblob = in.Bytes()
			}
		case "col_mediumtext_1":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColMediumtext1).UnmarshalJSON(data))
			}
		case "col_mediumtext_2":
			out.ColMediumtext2 = string(in.String())
		case "col_smallint_1":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColSmallint1).UnmarshalJSON(data))
			}
		case "col_smallint_2":
			out.ColSmallint2 = int32(in.Int32())
		case "col_smallint_3":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColSmallint3).UnmarshalJSON(data))
			}
		case "col_smallint_4":
			out.ColSmallint4 = uint32(in.Uint32())
		case "has_smallint_5":
			out.HasSmallint5 = bool(in.Bool())
		case "is_smallint_5":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.IsSmallint5).UnmarshalJSON(data))
			}
		case "col_text":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColText).UnmarshalJSON(data))
			}
		case "col_timestamp_1":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColTimestamp1).UnmarshalJSON(data))
			}
		case "col_timestamp_2":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColTimestamp2).UnmarshalJSON(data))
			}
		case "col_tinyint_1":
			out.ColTinyint1 = int32(in.Int32())
		case "col_varchar_1":
			out.ColVarchar1 = string(in.String())
		case "col_varchar_100":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColVarchar100).UnmarshalJSON(data))
			}
		case "col_varchar_16":
			out.ColVarchar16 = string(in.String())
		case "col_char_1":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ColChar1).UnmarshalJSON(data))
			}
		case "col_char_2":
			out.ColChar2 = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated1(out *jwriter.Writer, in DmlgenTypes) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.ID))
	}
	if true {
		const prefix string = ",\"col_bigint_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColBigint1).MarshalJSON())
	}
	if in.ColBigint2 != 0 {
		const prefix string = ",\"col_bigint_2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.ColBigint2))
	}
	if true {
		const prefix string = ",\"col_bigint_3\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColBigint3).MarshalJSON())
	}
	if in.ColBigint4 != 0 {
		const prefix string = ",\"col_bigint_4\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint64(uint64(in.ColBigint4))
	}
	if len(in.ColBlob) != 0 {
		const prefix string = ",\"col_blob\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Base64Bytes(in.ColBlob)
	}
	if true {
		const prefix string = ",\"col_date_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColDate1).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_date_2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColDate2).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_datetime_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColDatetime1).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_datetime_2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColDatetime2).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_decimal_10_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColDecimal101).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_decimal_12_4\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColDecimal124).MarshalJSON())
	}
	if true {
		const prefix string = ",\"price_12_4a\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Price124a).MarshalJSON())
	}
	if true {
		const prefix string = ",\"price_12_4b\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Price124b).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_decimal_12_3\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColDecimal123).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_decimal_20_6\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColDecimal206).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_decimal_24_12\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColDecimal2412).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_int_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColInt1).MarshalJSON())
	}
	if in.ColInt2 != 0 {
		const prefix string = ",\"col_int_2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.ColInt2))
	}
	if true {
		const prefix string = ",\"col_int_3\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColInt3).MarshalJSON())
	}
	if in.ColInt4 != 0 {
		const prefix string = ",\"col_int_4\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint32(uint32(in.ColInt4))
	}
	if true {
		const prefix string = ",\"col_longtext_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColLongtext1).MarshalJSON())
	}
	if in.ColLongtext2 != "" {
		const prefix string = ",\"col_longtext_2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ColLongtext2))
	}
	if len(in.ColMediumblob) != 0 {
		const prefix string = ",\"col_mediumblob\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Base64Bytes(in.ColMediumblob)
	}
	if true {
		const prefix string = ",\"col_mediumtext_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColMediumtext1).MarshalJSON())
	}
	if in.ColMediumtext2 != "" {
		const prefix string = ",\"col_mediumtext_2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ColMediumtext2))
	}
	if true {
		const prefix string = ",\"col_smallint_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColSmallint1).MarshalJSON())
	}
	if in.ColSmallint2 != 0 {
		const prefix string = ",\"col_smallint_2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.ColSmallint2))
	}
	if true {
		const prefix string = ",\"col_smallint_3\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColSmallint3).MarshalJSON())
	}
	if in.ColSmallint4 != 0 {
		const prefix string = ",\"col_smallint_4\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint32(uint32(in.ColSmallint4))
	}
	if in.HasSmallint5 {
		const prefix string = ",\"has_smallint_5\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.HasSmallint5))
	}
	if true {
		const prefix string = ",\"is_smallint_5\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.IsSmallint5).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_text\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColText).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_timestamp_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColTimestamp1).MarshalJSON())
	}
	if true {
		const prefix string = ",\"col_timestamp_2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColTimestamp2).MarshalJSON())
	}
	if in.ColTinyint1 != 0 {
		const prefix string = ",\"col_tinyint_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.ColTinyint1))
	}
	if in.ColVarchar1 != "" {
		const prefix string = ",\"col_varchar_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ColVarchar1))
	}
	if true {
		const prefix string = ",\"col_varchar_100\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColVarchar100).MarshalJSON())
	}
	if in.ColVarchar16 != "" {
		const prefix string = ",\"col_varchar_16\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ColVarchar16))
	}
	if true {
		const prefix string = ",\"col_char_1\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ColChar1).MarshalJSON())
	}
	if in.ColChar2 != "" {
		const prefix string = ",\"col_char_2\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ColChar2))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DmlgenTypes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DmlgenTypes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DmlgenTypes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DmlgenTypes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated1(l, v)
}
func easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated2(in *jlexer.Lexer, out *CoreConfigDataCollection) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]*CoreConfigData, 0, 8)
					} else {
						out.Data = []*CoreConfigData{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v10 *CoreConfigData
					if in.IsNull() {
						in.Skip()
						v10 = nil
					} else {
						if v10 == nil {
							v10 = new(CoreConfigData)
						}
						(*v10).UnmarshalEasyJSON(in)
					}
					out.Data = append(out.Data, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated2(out *jwriter.Writer, in CoreConfigDataCollection) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v11, v12 := range in.Data {
				if v11 > 0 {
					out.RawByte(',')
				}
				if v12 == nil {
					out.RawString("null")
				} else {
					(*v12).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CoreConfigDataCollection) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CoreConfigDataCollection) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CoreConfigDataCollection) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CoreConfigDataCollection) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated2(l, v)
}
func easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated3(in *jlexer.Lexer, out *CoreConfigData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "config_id":
			out.ConfigID = uint32(in.Uint32())
		case "scope":
			out.Scope = string(in.String())
		case "scope_id":
			out.ScopeID = int32(in.Int32())
		case "expires":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Expires).UnmarshalJSON(data))
			}
		case "x_path":
			out.Path = string(in.String())
		case "value":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Value).UnmarshalJSON(data))
			}
		case "version_ts":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.VersionTs).UnmarshalJSON(data))
			}
		case "version_te":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.VersionTe).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated3(out *jwriter.Writer, in CoreConfigData) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ConfigID != 0 {
		const prefix string = ",\"config_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint32(uint32(in.ConfigID))
	}
	if in.Scope != "" {
		const prefix string = ",\"scope\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Scope))
	}
	if in.ScopeID != 0 {
		const prefix string = ",\"scope_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.ScopeID))
	}
	if true {
		const prefix string = ",\"expires\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Expires).MarshalJSON())
	}
	if in.Path != "" {
		const prefix string = ",\"x_path\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Path))
	}
	if true {
		const prefix string = ",\"value\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Value).MarshalJSON())
	}
	if true {
		const prefix string = ",\"version_ts\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.VersionTs).MarshalJSON())
	}
	if true {
		const prefix string = ",\"version_te\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.VersionTe).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CoreConfigData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CoreConfigData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4b0a353eEncodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CoreConfigData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CoreConfigData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4b0a353eDecodeGithubComCorestoreioPkgSqlDmlgenDmltestgenerated3(l, v)
}
