// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  dmltestgenerated

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CoreConfiguration ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CoreConfiguration ) UnmarshalJSON([]byte) error { return nil }
func ( CoreConfiguration ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CoreConfiguration ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CoreConfiguration *CoreConfiguration

func ( CoreConfigurations ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CoreConfigurations ) UnmarshalJSON([]byte) error { return nil }
func ( CoreConfigurations ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CoreConfigurations ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CoreConfigurations *CoreConfigurations

func ( CustomerAddressEntities ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CustomerAddressEntities ) UnmarshalJSON([]byte) error { return nil }
func ( CustomerAddressEntities ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CustomerAddressEntities ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CustomerAddressEntities *CustomerAddressEntities

func ( CustomerAddressEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CustomerAddressEntity ) UnmarshalJSON([]byte) error { return nil }
func ( CustomerAddressEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CustomerAddressEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CustomerAddressEntity *CustomerAddressEntity

func ( CustomerEntities ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CustomerEntities ) UnmarshalJSON([]byte) error { return nil }
func ( CustomerEntities ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CustomerEntities ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CustomerEntities *CustomerEntities

func ( CustomerEntity ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CustomerEntity ) UnmarshalJSON([]byte) error { return nil }
func ( CustomerEntity ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CustomerEntity ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CustomerEntity *CustomerEntity

func ( DmlgenTypes ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DmlgenTypes ) UnmarshalJSON([]byte) error { return nil }
func ( DmlgenTypes ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DmlgenTypes ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DmlgenTypes *DmlgenTypes

func ( DmlgenTypesCollection ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DmlgenTypesCollection ) UnmarshalJSON([]byte) error { return nil }
func ( DmlgenTypesCollection ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DmlgenTypesCollection ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DmlgenTypesCollection *DmlgenTypesCollection

func ( SalesOrderStatusState ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SalesOrderStatusState ) UnmarshalJSON([]byte) error { return nil }
func ( SalesOrderStatusState ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SalesOrderStatusState ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SalesOrderStatusState *SalesOrderStatusState

func ( SalesOrderStatusStates ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SalesOrderStatusStates ) UnmarshalJSON([]byte) error { return nil }
func ( SalesOrderStatusStates ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SalesOrderStatusStates ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SalesOrderStatusStates *SalesOrderStatusStates

func ( ViewCustomerAutoIncrement ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ViewCustomerAutoIncrement ) UnmarshalJSON([]byte) error { return nil }
func ( ViewCustomerAutoIncrement ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ViewCustomerAutoIncrement ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ViewCustomerAutoIncrement *ViewCustomerAutoIncrement

func ( ViewCustomerAutoIncrements ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ViewCustomerAutoIncrements ) UnmarshalJSON([]byte) error { return nil }
func ( ViewCustomerAutoIncrements ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ViewCustomerAutoIncrements ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ViewCustomerAutoIncrements *ViewCustomerAutoIncrements

func ( ViewCustomerNoAutoIncrement ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ViewCustomerNoAutoIncrement ) UnmarshalJSON([]byte) error { return nil }
func ( ViewCustomerNoAutoIncrement ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ViewCustomerNoAutoIncrement ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ViewCustomerNoAutoIncrement *ViewCustomerNoAutoIncrement

func ( ViewCustomerNoAutoIncrements ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ViewCustomerNoAutoIncrements ) UnmarshalJSON([]byte) error { return nil }
func ( ViewCustomerNoAutoIncrements ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ViewCustomerNoAutoIncrements ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ViewCustomerNoAutoIncrements *ViewCustomerNoAutoIncrements
