// The MIT License (MIT)
//
// Copyright (c) 2014 Alex Saskevich
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package validation

// ISO3166Entry stores country codes
type ISO3166Entry struct {
	EnglishShortName string
	FrenchShortName  string
	Alpha2Code       string
	Alpha3Code       string
	Numeric          string
}

// ISO3166List based on https://www.iso.org/obp/ui/#search/code/ Code Type "Officially Assigned Codes"
var ISO3166List = []ISO3166Entry{
	{"Afghanistan", "Afghanistan (l')", "AF", "AFG", "004"},
	{"Albania", "Albanie (l')", "AL", "ALB", "008"},
	{"Antarctica", "Antarctique (l')", "AQ", "ATA", "010"},
	{"Algeria", "Algérie (l')", "DZ", "DZA", "012"},
	{"American Samoa", "Samoa américaines (les)", "AS", "ASM", "016"},
	{"Andorra", "Andorre (l')", "AD", "AND", "020"},
	{"Angola", "Angola (l')", "AO", "AGO", "024"},
	{"Antigua and Barbuda", "Antigua-et-Barbuda", "AG", "ATG", "028"},
	{"Azerbaijan", "Azerbaïdjan (l')", "AZ", "AZE", "031"},
	{"Argentina", "Argentine (l')", "AR", "ARG", "032"},
	{"Australia", "Australie (l')", "AU", "AUS", "036"},
	{"Austria", "Autriche (l')", "AT", "AUT", "040"},
	{"Bahamas (the)", "Bahamas (les)", "BS", "BHS", "044"},
	{"Bahrain", "Bahreïn", "BH", "BHR", "048"},
	{"Bangladesh", "Bangladesh (le)", "BD", "BGD", "050"},
	{"Armenia", "Arménie (l')", "AM", "ARM", "051"},
	{"Barbados", "Barbade (la)", "BB", "BRB", "052"},
	{"Belgium", "Belgique (la)", "BE", "BEL", "056"},
	{"Bermuda", "Bermudes (les)", "BM", "BMU", "060"},
	{"Bhutan", "Bhoutan (le)", "BT", "BTN", "064"},
	{"Bolivia (Plurinational State of)", "Bolivie (État plurinational de)", "BO", "BOL", "068"},
	{"Bosnia and Herzegovina", "Bosnie-Herzégovine (la)", "BA", "BIH", "070"},
	{"Botswana", "Botswana (le)", "BW", "BWA", "072"},
	{"Bouvet Island", "Bouvet (l'Île)", "BV", "BVT", "074"},
	{"Brazil", "Brésil (le)", "BR", "BRA", "076"},
	{"Belize", "Belize (le)", "BZ", "BLZ", "084"},
	{"British Indian Ocean Territory (the)", "Indien (le Territoire britannique de l'océan)", "IO", "IOT", "086"},
	{"Solomon Islands", "Salomon (Îles)", "SB", "SLB", "090"},
	{"Virgin Islands (British)", "Vierges britanniques (les Îles)", "VG", "VGB", "092"},
	{"Brunei Darussalam", "Brunéi Darussalam (le)", "BN", "BRN", "096"},
	{"Bulgaria", "Bulgarie (la)", "BG", "BGR", "100"},
	{"Myanmar", "Myanmar (le)", "MM", "MMR", "104"},
	{"Burundi", "Burundi (le)", "BI", "BDI", "108"},
	{"Belarus", "Bélarus (le)", "BY", "BLR", "112"},
	{"Cambodia", "Cambodge (le)", "KH", "KHM", "116"},
	{"Cameroon", "Cameroun (le)", "CM", "CMR", "120"},
	{"Canada", "Canada (le)", "CA", "CAN", "124"},
	{"Cabo Verde", "Cabo Verde", "CV", "CPV", "132"},
	{"Cayman Islands (the)", "Caïmans (les Îles)", "KY", "CYM", "136"},
	{"Central African Republic (the)", "République centrafricaine (la)", "CF", "CAF", "140"},
	{"Sri Lanka", "Sri Lanka", "LK", "LKA", "144"},
	{"Chad", "Tchad (le)", "TD", "TCD", "148"},
	{"Chile", "Chili (le)", "CL", "CHL", "152"},
	{"China", "Chine (la)", "CN", "CHN", "156"},
	{"Taiwan (Province of China)", "Taïwan (Province de Chine)", "TW", "TWN", "158"},
	{"Christmas Island", "Christmas (l'Île)", "CX", "CXR", "162"},
	{"Cocos (Keeling) Islands (the)", "Cocos (les Îles)/ Keeling (les Îles)", "CC", "CCK", "166"},
	{"Colombia", "Colombie (la)", "CO", "COL", "170"},
	{"Comoros (the)", "Comores (les)", "KM", "COM", "174"},
	{"Mayotte", "Mayotte", "YT", "MYT", "175"},
	{"Congo (the)", "Congo (le)", "CG", "COG", "178"},
	{"Congo (the Democratic Republic of the)", "Congo (la République démocratique du)", "CD", "COD", "180"},
	{"Cook Islands (the)", "Cook (les Îles)", "CK", "COK", "184"},
	{"Costa Rica", "Costa Rica (le)", "CR", "CRI", "188"},
	{"Croatia", "Croatie (la)", "HR", "HRV", "191"},
	{"Cuba", "Cuba", "CU", "CUB", "192"},
	{"Cyprus", "Chypre", "CY", "CYP", "196"},
	{"Czech Republic (the)", "tchèque (la République)", "CZ", "CZE", "203"},
	{"Benin", "Bénin (le)", "BJ", "BEN", "204"},
	{"Denmark", "Danemark (le)", "DK", "DNK", "208"},
	{"Dominica", "Dominique (la)", "DM", "DMA", "212"},
	{"Dominican Republic (the)", "dominicaine (la République)", "DO", "DOM", "214"},
	{"Ecuador", "Équateur (l')", "EC", "ECU", "218"},
	{"El Salvador", "El Salvador", "SV", "SLV", "222"},
	{"Equatorial Guinea", "Guinée équatoriale (la)", "GQ", "GNQ", "226"},
	{"Ethiopia", "Éthiopie (l')", "ET", "ETH", "231"},
	{"Eritrea", "Érythrée (l')", "ER", "ERI", "232"},
	{"Estonia", "Estonie (l')", "EE", "EST", "233"},
	{"Faroe Islands (the)", "Féroé (les Îles)", "FO", "FRO", "234"},
	{"Falkland Islands (the) [Malvinas]", "Falkland (les Îles)/Malouines (les Îles)", "FK", "FLK", "238"},
	{"South Georgia and the South Sandwich Islands", "Géorgie du Sud-et-les Îles Sandwich du Sud (la)", "GS", "SGS", "239"},
	{"Fiji", "Fidji (les)", "FJ", "FJI", "242"},
	{"Finland", "Finlande (la)", "FI", "FIN", "246"},
	{"Åland Islands", "Åland(les Îles)", "AX", "ALA", "248"},
	{"France", "France (la)", "FR", "FRA", "250"},
	{"French Guiana", "Guyane française (la )", "GF", "GUF", "254"},
	{"French Polynesia", "Polynésie française (la)", "PF", "PYF", "258"},
	{"French Southern Territories (the)", "Terres australes françaises (les)", "TF", "ATF", "260"},
	{"Djibouti", "Djibouti", "DJ", "DJI", "262"},
	{"Gabon", "Gabon (le)", "GA", "GAB", "266"},
	{"Georgia", "Géorgie (la)", "GE", "GEO", "268"},
	{"Gambia (the)", "Gambie (la)", "GM", "GMB", "270"},
	{"Palestine, State of", "Palestine, État de", "PS", "PSE", "275"},
	{"Germany", "Allemagne (l')", "DE", "DEU", "276"},
	{"Ghana", "Ghana (le)", "GH", "GHA", "288"},
	{"Gibraltar", "Gibraltar", "GI", "GIB", "292"},
	{"Kiribati", "Kiribati", "KI", "KIR", "296"},
	{"Greece", "Grèce (la)", "GR", "GRC", "300"},
	{"Greenland", "Groenland (le)", "GL", "GRL", "304"},
	{"Grenada", "Grenade (la)", "GD", "GRD", "308"},
	{"Guadeloupe", "Guadeloupe (la)", "GP", "GLP", "312"},
	{"Guam", "Guam", "GU", "GUM", "316"},
	{"Guatemala", "Guatemala (le)", "GT", "GTM", "320"},
	{"Guinea", "Guinée (la)", "GN", "GIN", "324"},
	{"Guyana", "Guyana (le)", "GY", "GUY", "328"},
	{"Haiti", "Haïti", "HT", "HTI", "332"},
	{"Heard Island and McDonald Islands", "Heard-et-Îles MacDonald (l'Île)", "HM", "HMD", "334"},
	{"Holy See (the)", "Saint-Siège (le)", "VA", "VAT", "336"},
	{"Honduras", "Honduras (le)", "HN", "HND", "340"},
	{"Hong Kong", "Hong Kong", "HK", "HKG", "344"},
	{"Hungary", "Hongrie (la)", "HU", "HUN", "348"},
	{"Iceland", "Islande (l')", "IS", "ISL", "352"},
	{"India", "Inde (l')", "IN", "IND", "356"},
	{"Indonesia", "Indonésie (l')", "ID", "IDN", "360"},
	{"Iran (Islamic Republic of)", "Iran (République Islamique d')", "IR", "IRN", "364"},
	{"Iraq", "Iraq (l')", "IQ", "IRQ", "368"},
	{"Ireland", "Irlande (l')", "IE", "IRL", "372"},
	{"Israel", "Israël", "IL", "ISR", "376"},
	{"Italy", "Italie (l')", "IT", "ITA", "380"},
	{"Côte d'Ivoire", "Côte d'Ivoire (la)", "CI", "CIV", "384"},
	{"Jamaica", "Jamaïque (la)", "JM", "JAM", "388"},
	{"Japan", "Japon (le)", "JP", "JPN", "392"},
	{"Kazakhstan", "Kazakhstan (le)", "KZ", "KAZ", "398"},
	{"Jordan", "Jordanie (la)", "JO", "JOR", "400"},
	{"Kenya", "Kenya (le)", "KE", "KEN", "404"},
	{"Korea (the Democratic People's Republic of)", "Corée (la République populaire démocratique de)", "KP", "PRK", "408"},
	{"Korea (the Republic of)", "Corée (la République de)", "KR", "KOR", "410"},
	{"Kuwait", "Koweït (le)", "KW", "KWT", "414"},
	{"Kyrgyzstan", "Kirghizistan (le)", "KG", "KGZ", "417"},
	{"Lao People's Democratic Republic (the)", "Lao, République démocratique populaire", "LA", "LAO", "418"},
	{"Lebanon", "Liban (le)", "LB", "LBN", "422"},
	{"Lesotho", "Lesotho (le)", "LS", "LSO", "426"},
	{"Latvia", "Lettonie (la)", "LV", "LVA", "428"},
	{"Liberia", "Libéria (le)", "LR", "LBR", "430"},
	{"Libya", "Libye (la)", "LY", "LBY", "434"},
	{"Liechtenstein", "Liechtenstein (le)", "LI", "LIE", "438"},
	{"Lithuania", "Lituanie (la)", "LT", "LTU", "440"},
	{"Luxembourg", "Luxembourg (le)", "LU", "LUX", "442"},
	{"Macao", "Macao", "MO", "MAC", "446"},
	{"Madagascar", "Madagascar", "MG", "MDG", "450"},
	{"Malawi", "Malawi (le)", "MW", "MWI", "454"},
	{"Malaysia", "Malaisie (la)", "MY", "MYS", "458"},
	{"Maldives", "Maldives (les)", "MV", "MDV", "462"},
	{"Mali", "Mali (le)", "ML", "MLI", "466"},
	{"Malta", "Malte", "MT", "MLT", "470"},
	{"Martinique", "Martinique (la)", "MQ", "MTQ", "474"},
	{"Mauritania", "Mauritanie (la)", "MR", "MRT", "478"},
	{"Mauritius", "Maurice", "MU", "MUS", "480"},
	{"Mexico", "Mexique (le)", "MX", "MEX", "484"},
	{"Monaco", "Monaco", "MC", "MCO", "492"},
	{"Mongolia", "Mongolie (la)", "MN", "MNG", "496"},
	{"Moldova (the Republic of)", "Moldova , République de", "MD", "MDA", "498"},
	{"Montenegro", "Monténégro (le)", "ME", "MNE", "499"},
	{"Montserrat", "Montserrat", "MS", "MSR", "500"},
	{"Morocco", "Maroc (le)", "MA", "MAR", "504"},
	{"Mozambique", "Mozambique (le)", "MZ", "MOZ", "508"},
	{"Oman", "Oman", "OM", "OMN", "512"},
	{"Namibia", "Namibie (la)", "NA", "NAM", "516"},
	{"Nauru", "Nauru", "NR", "NRU", "520"},
	{"Nepal", "Népal (le)", "NP", "NPL", "524"},
	{"Netherlands (the)", "Pays-Bas (les)", "NL", "NLD", "528"},
	{"Curaçao", "Curaçao", "CW", "CUW", "531"},
	{"Aruba", "Aruba", "AW", "ABW", "533"},
	{"Sint Maarten (Dutch part)", "Saint-Martin (partie néerlandaise)", "SX", "SXM", "534"},
	{"Bonaire, Sint Eustatius and Saba", "Bonaire, Saint-Eustache et Saba", "BQ", "BES", "535"},
	{"New Caledonia", "Nouvelle-Calédonie (la)", "NC", "NCL", "540"},
	{"Vanuatu", "Vanuatu (le)", "VU", "VUT", "548"},
	{"New Zealand", "Nouvelle-Zélande (la)", "NZ", "NZL", "554"},
	{"Nicaragua", "Nicaragua (le)", "NI", "NIC", "558"},
	{"Niger (the)", "Niger (le)", "NE", "NER", "562"},
	{"Nigeria", "Nigéria (le)", "NG", "NGA", "566"},
	{"Niue", "Niue", "NU", "NIU", "570"},
	{"Norfolk Island", "Norfolk (l'Île)", "NF", "NFK", "574"},
	{"Norway", "Norvège (la)", "NO", "NOR", "578"},
	{"Northern Mariana Islands (the)", "Mariannes du Nord (les Îles)", "MP", "MNP", "580"},
	{"United States Minor Outlying Islands (the)", "Îles mineures éloignées des États-Unis (les)", "UM", "UMI", "581"},
	{"Micronesia (Federated States of)", "Micronésie (États fédérés de)", "FM", "FSM", "583"},
	{"Marshall Islands (the)", "Marshall (Îles)", "MH", "MHL", "584"},
	{"Palau", "Palaos (les)", "PW", "PLW", "585"},
	{"Pakistan", "Pakistan (le)", "PK", "PAK", "586"},
	{"Panama", "Panama (le)", "PA", "PAN", "591"},
	{"Papua New Guinea", "Papouasie-Nouvelle-Guinée (la)", "PG", "PNG", "598"},
	{"Paraguay", "Paraguay (le)", "PY", "PRY", "600"},
	{"Peru", "Pérou (le)", "PE", "PER", "604"},
	{"Philippines (the)", "Philippines (les)", "PH", "PHL", "608"},
	{"Pitcairn", "Pitcairn", "PN", "PCN", "612"},
	{"Poland", "Pologne (la)", "PL", "POL", "616"},
	{"Portugal", "Portugal (le)", "PT", "PRT", "620"},
	{"Guinea-Bissau", "Guinée-Bissau (la)", "GW", "GNB", "624"},
	{"Timor-Leste", "Timor-Leste (le)", "TL", "TLS", "626"},
	{"Puerto Rico", "Porto Rico", "PR", "PRI", "630"},
	{"Qatar", "Qatar (le)", "QA", "QAT", "634"},
	{"Réunion", "Réunion (La)", "RE", "REU", "638"},
	{"Romania", "Roumanie (la)", "RO", "ROU", "642"},
	{"Russian Federation (the)", "Russie (la Fédération de)", "RU", "RUS", "643"},
	{"Rwanda", "Rwanda (le)", "RW", "RWA", "646"},
	{"Saint Barthélemy", "Saint-Barthélemy", "BL", "BLM", "652"},
	{"Saint Helena, Ascension and Tristan da Cunha", "Sainte-Hélène, Ascension et Tristan da Cunha", "SH", "SHN", "654"},
	{"Saint Kitts and Nevis", "Saint-Kitts-et-Nevis", "KN", "KNA", "659"},
	{"Anguilla", "Anguilla", "AI", "AIA", "660"},
	{"Saint Lucia", "Sainte-Lucie", "LC", "LCA", "662"},
	{"Saint Martin (French part)", "Saint-Martin (partie française)", "MF", "MAF", "663"},
	{"Saint Pierre and Miquelon", "Saint-Pierre-et-Miquelon", "PM", "SPM", "666"},
	{"Saint Vincent and the Grenadines", "Saint-Vincent-et-les Grenadines", "VC", "VCT", "670"},
	{"San Marino", "Saint-Marin", "SM", "SMR", "674"},
	{"Sao Tome and Principe", "Sao Tomé-et-Principe", "ST", "STP", "678"},
	{"Saudi Arabia", "Arabie saoudite (l')", "SA", "SAU", "682"},
	{"Senegal", "Sénégal (le)", "SN", "SEN", "686"},
	{"Serbia", "Serbie (la)", "RS", "SRB", "688"},
	{"Seychelles", "Seychelles (les)", "SC", "SYC", "690"},
	{"Sierra Leone", "Sierra Leone (la)", "SL", "SLE", "694"},
	{"Singapore", "Singapour", "SG", "SGP", "702"},
	{"Slovakia", "Slovaquie (la)", "SK", "SVK", "703"},
	{"Viet Nam", "Viet Nam (le)", "VN", "VNM", "704"},
	{"Slovenia", "Slovénie (la)", "SI", "SVN", "705"},
	{"Somalia", "Somalie (la)", "SO", "SOM", "706"},
	{"South Africa", "Afrique du Sud (l')", "ZA", "ZAF", "710"},
	{"Zimbabwe", "Zimbabwe (le)", "ZW", "ZWE", "716"},
	{"Spain", "Espagne (l')", "ES", "ESP", "724"},
	{"South Sudan", "Soudan du Sud (le)", "SS", "SSD", "728"},
	{"Sudan (the)", "Soudan (le)", "SD", "SDN", "729"},
	{"Western Sahara*", "Sahara occidental (le)*", "EH", "ESH", "732"},
	{"Suriname", "Suriname (le)", "SR", "SUR", "740"},
	{"Svalbard and Jan Mayen", "Svalbard et l'Île Jan Mayen (le)", "SJ", "SJM", "744"},
	{"Swaziland", "Swaziland (le)", "SZ", "SWZ", "748"},
	{"Sweden", "Suède (la)", "SE", "SWE", "752"},
	{"Switzerland", "Suisse (la)", "CH", "CHE", "756"},
	{"Syrian Arab Republic", "République arabe syrienne (la)", "SY", "SYR", "760"},
	{"Tajikistan", "Tadjikistan (le)", "TJ", "TJK", "762"},
	{"Thailand", "Thaïlande (la)", "TH", "THA", "764"},
	{"Togo", "Togo (le)", "TG", "TGO", "768"},
	{"Tokelau", "Tokelau (les)", "TK", "TKL", "772"},
	{"Tonga", "Tonga (les)", "TO", "TON", "776"},
	{"Trinidad and Tobago", "Trinité-et-Tobago (la)", "TT", "TTO", "780"},
	{"United Arab Emirates (the)", "Émirats arabes unis (les)", "AE", "ARE", "784"},
	{"Tunisia", "Tunisie (la)", "TN", "TUN", "788"},
	{"Turkey", "Turquie (la)", "TR", "TUR", "792"},
	{"Turkmenistan", "Turkménistan (le)", "TM", "TKM", "795"},
	{"Turks and Caicos Islands (the)", "Turks-et-Caïcos (les Îles)", "TC", "TCA", "796"},
	{"Tuvalu", "Tuvalu (les)", "TV", "TUV", "798"},
	{"Uganda", "Ouganda (l')", "UG", "UGA", "800"},
	{"Ukraine", "Ukraine (l')", "UA", "UKR", "804"},
	{"Macedonia (the former Yugoslav Republic of)", "Macédoine (l'ex‑République yougoslave de)", "MK", "MKD", "807"},
	{"Egypt", "Égypte (l')", "EG", "EGY", "818"},
	{"United Kingdom of Great Britain and Northern Ireland (the)", "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)", "GB", "GBR", "826"},
	{"Guernsey", "Guernesey", "GG", "GGY", "831"},
	{"Jersey", "Jersey", "JE", "JEY", "832"},
	{"Isle of Man", "Île de Man", "IM", "IMN", "833"},
	{"Tanzania, United Republic of", "Tanzanie, République-Unie de", "TZ", "TZA", "834"},
	{"United States of America (the)", "États-Unis d'Amérique (les)", "US", "USA", "840"},
	{"Virgin Islands (U.S.)", "Vierges des États-Unis (les Îles)", "VI", "VIR", "850"},
	{"Burkina Faso", "Burkina Faso (le)", "BF", "BFA", "854"},
	{"Uruguay", "Uruguay (l')", "UY", "URY", "858"},
	{"Uzbekistan", "Ouzbékistan (l')", "UZ", "UZB", "860"},
	{"Venezuela (Bolivarian Republic of)", "Venezuela (République bolivarienne du)", "VE", "VEN", "862"},
	{"Wallis and Futuna", "Wallis-et-Futuna", "WF", "WLF", "876"},
	{"Samoa", "Samoa (le)", "WS", "WSM", "882"},
	{"Yemen", "Yémen (le)", "YE", "YEM", "887"},
	{"Zambia", "Zambie (la)", "ZM", "ZMB", "894"},
}

// iso4217List is the list of ISO currency codes. Do not change the map or you
// cause race conditions.
var iso4217List = map[string]bool{
	"AED": true, "AFN": true, "ALL": true, "AMD": true, "ANG": true, "AOA": true, "ARS": true, "AUD": true, "AWG": true, "AZN": true,
	"BAM": true, "BBD": true, "BDT": true, "BGN": true, "BHD": true, "BIF": true, "BMD": true, "BND": true, "BOB": true, "BOV": true, "BRL": true, "BSD": true, "BTN": true, "BWP": true, "BYN": true, "BZD": true,
	"CAD": true, "CDF": true, "CHE": true, "CHF": true, "CHW": true, "CLF": true, "CLP": true, "CNY": true, "COP": true, "COU": true, "CRC": true, "CUC": true, "CUP": true, "CVE": true, "CZK": true,
	"DJF": true, "DKK": true, "DOP": true, "DZD": true,
	"EGP": true, "ERN": true, "ETB": true, "EUR": true,
	"FJD": true, "FKP": true,
	"GBP": true, "GEL": true, "GHS": true, "GIP": true, "GMD": true, "GNF": true, "GTQ": true, "GYD": true,
	"HKD": true, "HNL": true, "HRK": true, "HTG": true, "HUF": true,
	"IDR": true, "ILS": true, "INR": true, "IQD": true, "IRR": true, "ISK": true,
	"JMD": true, "JOD": true, "JPY": true,
	"KES": true, "KGS": true, "KHR": true, "KMF": true, "KPW": true, "KRW": true, "KWD": true, "KYD": true, "KZT": true,
	"LAK": true, "LBP": true, "LKR": true, "LRD": true, "LSL": true, "LYD": true,
	"MAD": true, "MDL": true, "MGA": true, "MKD": true, "MMK": true, "MNT": true, "MOP": true, "MRO": true, "MUR": true, "MVR": true, "MWK": true, "MXN": true, "MXV": true, "MYR": true, "MZN": true,
	"NAD": true, "NGN": true, "NIO": true, "NOK": true, "NPR": true, "NZD": true,
	"OMR": true,
	"PAB": true, "PEN": true, "PGK": true, "PHP": true, "PKR": true, "PLN": true, "PYG": true,
	"QAR": true,
	"RON": true, "RSD": true, "RUB": true, "RWF": true,
	"SAR": true, "SBD": true, "SCR": true, "SDG": true, "SEK": true, "SGD": true, "SHP": true, "SLL": true, "SOS": true, "SRD": true, "SSP": true, "STD": true, "SVC": true, "SYP": true, "SZL": true,
	"THB": true, "TJS": true, "TMT": true, "TND": true, "TOP": true, "TRY": true, "TTD": true, "TWD": true, "TZS": true,
	"UAH": true, "UGX": true, "USD": true, "USN": true, "UYI": true, "UYU": true, "UZS": true,
	"VEF": true, "VND": true, "VUV": true,
	"WST": true,
	"XAF": true, "XAG": true, "XAU": true, "XBA": true, "XBB": true, "XBC": true, "XBD": true, "XCD": true, "XDR": true, "XOF": true, "XPD": true, "XPF": true, "XPT": true, "XSU": true, "XTS": true, "XUA": true, "XXX": true,
	"YER": true,
	"ZAR": true, "ZMW": true, "ZWL": true,
}

// ISO693Entry stores ISO language codes
type ISO693Entry struct {
	Alpha3bCode string
	Alpha2Code  string
	English     string
}

// ISO693List based on http://data.okfn.org/data/core/language-codes/r/language-codes-3b2.json
var ISO693List = []ISO693Entry{
	{Alpha3bCode: "aar", Alpha2Code: "aa", English: "Afar"},
	{Alpha3bCode: "abk", Alpha2Code: "ab", English: "Abkhazian"},
	{Alpha3bCode: "afr", Alpha2Code: "af", English: "Afrikaans"},
	{Alpha3bCode: "aka", Alpha2Code: "ak", English: "Akan"},
	{Alpha3bCode: "alb", Alpha2Code: "sq", English: "Albanian"},
	{Alpha3bCode: "amh", Alpha2Code: "am", English: "Amharic"},
	{Alpha3bCode: "ara", Alpha2Code: "ar", English: "Arabic"},
	{Alpha3bCode: "arg", Alpha2Code: "an", English: "Aragonese"},
	{Alpha3bCode: "arm", Alpha2Code: "hy", English: "Armenian"},
	{Alpha3bCode: "asm", Alpha2Code: "as", English: "Assamese"},
	{Alpha3bCode: "ava", Alpha2Code: "av", English: "Avaric"},
	{Alpha3bCode: "ave", Alpha2Code: "ae", English: "Avestan"},
	{Alpha3bCode: "aym", Alpha2Code: "ay", English: "Aymara"},
	{Alpha3bCode: "aze", Alpha2Code: "az", English: "Azerbaijani"},
	{Alpha3bCode: "bak", Alpha2Code: "ba", English: "Bashkir"},
	{Alpha3bCode: "bam", Alpha2Code: "bm", English: "Bambara"},
	{Alpha3bCode: "baq", Alpha2Code: "eu", English: "Basque"},
	{Alpha3bCode: "bel", Alpha2Code: "be", English: "Belarusian"},
	{Alpha3bCode: "ben", Alpha2Code: "bn", English: "Bengali"},
	{Alpha3bCode: "bih", Alpha2Code: "bh", English: "Bihari languages"},
	{Alpha3bCode: "bis", Alpha2Code: "bi", English: "Bislama"},
	{Alpha3bCode: "bos", Alpha2Code: "bs", English: "Bosnian"},
	{Alpha3bCode: "bre", Alpha2Code: "br", English: "Breton"},
	{Alpha3bCode: "bul", Alpha2Code: "bg", English: "Bulgarian"},
	{Alpha3bCode: "bur", Alpha2Code: "my", English: "Burmese"},
	{Alpha3bCode: "cat", Alpha2Code: "ca", English: "Catalan; Valencian"},
	{Alpha3bCode: "cha", Alpha2Code: "ch", English: "Chamorro"},
	{Alpha3bCode: "che", Alpha2Code: "ce", English: "Chechen"},
	{Alpha3bCode: "chi", Alpha2Code: "zh", English: "Chinese"},
	{Alpha3bCode: "chu", Alpha2Code: "cu", English: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"},
	{Alpha3bCode: "chv", Alpha2Code: "cv", English: "Chuvash"},
	{Alpha3bCode: "cor", Alpha2Code: "kw", English: "Cornish"},
	{Alpha3bCode: "cos", Alpha2Code: "co", English: "Corsican"},
	{Alpha3bCode: "cre", Alpha2Code: "cr", English: "Cree"},
	{Alpha3bCode: "cze", Alpha2Code: "cs", English: "Czech"},
	{Alpha3bCode: "dan", Alpha2Code: "da", English: "Danish"},
	{Alpha3bCode: "div", Alpha2Code: "dv", English: "Divehi; Dhivehi; Maldivian"},
	{Alpha3bCode: "dut", Alpha2Code: "nl", English: "Dutch; Flemish"},
	{Alpha3bCode: "dzo", Alpha2Code: "dz", English: "Dzongkha"},
	{Alpha3bCode: "eng", Alpha2Code: "en", English: "English"},
	{Alpha3bCode: "epo", Alpha2Code: "eo", English: "Esperanto"},
	{Alpha3bCode: "est", Alpha2Code: "et", English: "Estonian"},
	{Alpha3bCode: "ewe", Alpha2Code: "ee", English: "Ewe"},
	{Alpha3bCode: "fao", Alpha2Code: "fo", English: "Faroese"},
	{Alpha3bCode: "fij", Alpha2Code: "fj", English: "Fijian"},
	{Alpha3bCode: "fin", Alpha2Code: "fi", English: "Finnish"},
	{Alpha3bCode: "fre", Alpha2Code: "fr", English: "French"},
	{Alpha3bCode: "fry", Alpha2Code: "fy", English: "Western Frisian"},
	{Alpha3bCode: "ful", Alpha2Code: "ff", English: "Fulah"},
	{Alpha3bCode: "geo", Alpha2Code: "ka", English: "Georgian"},
	{Alpha3bCode: "ger", Alpha2Code: "de", English: "German"},
	{Alpha3bCode: "gla", Alpha2Code: "gd", English: "Gaelic; Scottish Gaelic"},
	{Alpha3bCode: "gle", Alpha2Code: "ga", English: "Irish"},
	{Alpha3bCode: "glg", Alpha2Code: "gl", English: "Galician"},
	{Alpha3bCode: "glv", Alpha2Code: "gv", English: "Manx"},
	{Alpha3bCode: "gre", Alpha2Code: "el", English: "Greek, Modern (1453-)"},
	{Alpha3bCode: "grn", Alpha2Code: "gn", English: "Guarani"},
	{Alpha3bCode: "guj", Alpha2Code: "gu", English: "Gujarati"},
	{Alpha3bCode: "hat", Alpha2Code: "ht", English: "Haitian; Haitian Creole"},
	{Alpha3bCode: "hau", Alpha2Code: "ha", English: "Hausa"},
	{Alpha3bCode: "heb", Alpha2Code: "he", English: "Hebrew"},
	{Alpha3bCode: "her", Alpha2Code: "hz", English: "Herero"},
	{Alpha3bCode: "hin", Alpha2Code: "hi", English: "Hindi"},
	{Alpha3bCode: "hmo", Alpha2Code: "ho", English: "Hiri Motu"},
	{Alpha3bCode: "hrv", Alpha2Code: "hr", English: "Croatian"},
	{Alpha3bCode: "hun", Alpha2Code: "hu", English: "Hungarian"},
	{Alpha3bCode: "ibo", Alpha2Code: "ig", English: "Igbo"},
	{Alpha3bCode: "ice", Alpha2Code: "is", English: "Icelandic"},
	{Alpha3bCode: "ido", Alpha2Code: "io", English: "Ido"},
	{Alpha3bCode: "iii", Alpha2Code: "ii", English: "Sichuan Yi; Nuosu"},
	{Alpha3bCode: "iku", Alpha2Code: "iu", English: "Inuktitut"},
	{Alpha3bCode: "ile", Alpha2Code: "ie", English: "Interlingue; Occidental"},
	{Alpha3bCode: "ina", Alpha2Code: "ia", English: "Interlingua (International Auxiliary Language Association)"},
	{Alpha3bCode: "ind", Alpha2Code: "id", English: "Indonesian"},
	{Alpha3bCode: "ipk", Alpha2Code: "ik", English: "Inupiaq"},
	{Alpha3bCode: "ita", Alpha2Code: "it", English: "Italian"},
	{Alpha3bCode: "jav", Alpha2Code: "jv", English: "Javanese"},
	{Alpha3bCode: "jpn", Alpha2Code: "ja", English: "Japanese"},
	{Alpha3bCode: "kal", Alpha2Code: "kl", English: "Kalaallisut; Greenlandic"},
	{Alpha3bCode: "kan", Alpha2Code: "kn", English: "Kannada"},
	{Alpha3bCode: "kas", Alpha2Code: "ks", English: "Kashmiri"},
	{Alpha3bCode: "kau", Alpha2Code: "kr", English: "Kanuri"},
	{Alpha3bCode: "kaz", Alpha2Code: "kk", English: "Kazakh"},
	{Alpha3bCode: "khm", Alpha2Code: "km", English: "Central Khmer"},
	{Alpha3bCode: "kik", Alpha2Code: "ki", English: "Kikuyu; Gikuyu"},
	{Alpha3bCode: "kin", Alpha2Code: "rw", English: "Kinyarwanda"},
	{Alpha3bCode: "kir", Alpha2Code: "ky", English: "Kirghiz; Kyrgyz"},
	{Alpha3bCode: "kom", Alpha2Code: "kv", English: "Komi"},
	{Alpha3bCode: "kon", Alpha2Code: "kg", English: "Kongo"},
	{Alpha3bCode: "kor", Alpha2Code: "ko", English: "Korean"},
	{Alpha3bCode: "kua", Alpha2Code: "kj", English: "Kuanyama; Kwanyama"},
	{Alpha3bCode: "kur", Alpha2Code: "ku", English: "Kurdish"},
	{Alpha3bCode: "lao", Alpha2Code: "lo", English: "Lao"},
	{Alpha3bCode: "lat", Alpha2Code: "la", English: "Latin"},
	{Alpha3bCode: "lav", Alpha2Code: "lv", English: "Latvian"},
	{Alpha3bCode: "lim", Alpha2Code: "li", English: "Limburgan; Limburger; Limburgish"},
	{Alpha3bCode: "lin", Alpha2Code: "ln", English: "Lingala"},
	{Alpha3bCode: "lit", Alpha2Code: "lt", English: "Lithuanian"},
	{Alpha3bCode: "ltz", Alpha2Code: "lb", English: "Luxembourgish; Letzeburgesch"},
	{Alpha3bCode: "lub", Alpha2Code: "lu", English: "Luba-Katanga"},
	{Alpha3bCode: "lug", Alpha2Code: "lg", English: "Ganda"},
	{Alpha3bCode: "mac", Alpha2Code: "mk", English: "Macedonian"},
	{Alpha3bCode: "mah", Alpha2Code: "mh", English: "Marshallese"},
	{Alpha3bCode: "mal", Alpha2Code: "ml", English: "Malayalam"},
	{Alpha3bCode: "mao", Alpha2Code: "mi", English: "Maori"},
	{Alpha3bCode: "mar", Alpha2Code: "mr", English: "Marathi"},
	{Alpha3bCode: "may", Alpha2Code: "ms", English: "Malay"},
	{Alpha3bCode: "mlg", Alpha2Code: "mg", English: "Malagasy"},
	{Alpha3bCode: "mlt", Alpha2Code: "mt", English: "Maltese"},
	{Alpha3bCode: "mon", Alpha2Code: "mn", English: "Mongolian"},
	{Alpha3bCode: "nau", Alpha2Code: "na", English: "Nauru"},
	{Alpha3bCode: "nav", Alpha2Code: "nv", English: "Navajo; Navaho"},
	{Alpha3bCode: "nbl", Alpha2Code: "nr", English: "Ndebele, South; South Ndebele"},
	{Alpha3bCode: "nde", Alpha2Code: "nd", English: "Ndebele, North; North Ndebele"},
	{Alpha3bCode: "ndo", Alpha2Code: "ng", English: "Ndonga"},
	{Alpha3bCode: "nep", Alpha2Code: "ne", English: "Nepali"},
	{Alpha3bCode: "nno", Alpha2Code: "nn", English: "Norwegian Nynorsk; Nynorsk, Norwegian"},
	{Alpha3bCode: "nob", Alpha2Code: "nb", English: "Bokmål, Norwegian; Norwegian Bokmål"},
	{Alpha3bCode: "nor", Alpha2Code: "no", English: "Norwegian"},
	{Alpha3bCode: "nya", Alpha2Code: "ny", English: "Chichewa; Chewa; Nyanja"},
	{Alpha3bCode: "oci", Alpha2Code: "oc", English: "Occitan (post 1500); Provençal"},
	{Alpha3bCode: "oji", Alpha2Code: "oj", English: "Ojibwa"},
	{Alpha3bCode: "ori", Alpha2Code: "or", English: "Oriya"},
	{Alpha3bCode: "orm", Alpha2Code: "om", English: "Oromo"},
	{Alpha3bCode: "oss", Alpha2Code: "os", English: "Ossetian; Ossetic"},
	{Alpha3bCode: "pan", Alpha2Code: "pa", English: "Panjabi; Punjabi"},
	{Alpha3bCode: "per", Alpha2Code: "fa", English: "Persian"},
	{Alpha3bCode: "pli", Alpha2Code: "pi", English: "Pali"},
	{Alpha3bCode: "pol", Alpha2Code: "pl", English: "Polish"},
	{Alpha3bCode: "por", Alpha2Code: "pt", English: "Portuguese"},
	{Alpha3bCode: "pus", Alpha2Code: "ps", English: "Pushto; Pashto"},
	{Alpha3bCode: "que", Alpha2Code: "qu", English: "Quechua"},
	{Alpha3bCode: "roh", Alpha2Code: "rm", English: "Romansh"},
	{Alpha3bCode: "rum", Alpha2Code: "ro", English: "Romanian; Moldavian; Moldovan"},
	{Alpha3bCode: "run", Alpha2Code: "rn", English: "Rundi"},
	{Alpha3bCode: "rus", Alpha2Code: "ru", English: "Russian"},
	{Alpha3bCode: "sag", Alpha2Code: "sg", English: "Sango"},
	{Alpha3bCode: "san", Alpha2Code: "sa", English: "Sanskrit"},
	{Alpha3bCode: "sin", Alpha2Code: "si", English: "Sinhala; Sinhalese"},
	{Alpha3bCode: "slo", Alpha2Code: "sk", English: "Slovak"},
	{Alpha3bCode: "slv", Alpha2Code: "sl", English: "Slovenian"},
	{Alpha3bCode: "sme", Alpha2Code: "se", English: "Northern Sami"},
	{Alpha3bCode: "smo", Alpha2Code: "sm", English: "Samoan"},
	{Alpha3bCode: "sna", Alpha2Code: "sn", English: "Shona"},
	{Alpha3bCode: "snd", Alpha2Code: "sd", English: "Sindhi"},
	{Alpha3bCode: "som", Alpha2Code: "so", English: "Somali"},
	{Alpha3bCode: "sot", Alpha2Code: "st", English: "Sotho, Southern"},
	{Alpha3bCode: "spa", Alpha2Code: "es", English: "Spanish; Castilian"},
	{Alpha3bCode: "srd", Alpha2Code: "sc", English: "Sardinian"},
	{Alpha3bCode: "srp", Alpha2Code: "sr", English: "Serbian"},
	{Alpha3bCode: "ssw", Alpha2Code: "ss", English: "Swati"},
	{Alpha3bCode: "sun", Alpha2Code: "su", English: "Sundanese"},
	{Alpha3bCode: "swa", Alpha2Code: "sw", English: "Swahili"},
	{Alpha3bCode: "swe", Alpha2Code: "sv", English: "Swedish"},
	{Alpha3bCode: "tah", Alpha2Code: "ty", English: "Tahitian"},
	{Alpha3bCode: "tam", Alpha2Code: "ta", English: "Tamil"},
	{Alpha3bCode: "tat", Alpha2Code: "tt", English: "Tatar"},
	{Alpha3bCode: "tel", Alpha2Code: "te", English: "Telugu"},
	{Alpha3bCode: "tgk", Alpha2Code: "tg", English: "Tajik"},
	{Alpha3bCode: "tgl", Alpha2Code: "tl", English: "Tagalog"},
	{Alpha3bCode: "tha", Alpha2Code: "th", English: "Thai"},
	{Alpha3bCode: "tib", Alpha2Code: "bo", English: "Tibetan"},
	{Alpha3bCode: "tir", Alpha2Code: "ti", English: "Tigrinya"},
	{Alpha3bCode: "ton", Alpha2Code: "to", English: "Tonga (Tonga Islands)"},
	{Alpha3bCode: "tsn", Alpha2Code: "tn", English: "Tswana"},
	{Alpha3bCode: "tso", Alpha2Code: "ts", English: "Tsonga"},
	{Alpha3bCode: "tuk", Alpha2Code: "tk", English: "Turkmen"},
	{Alpha3bCode: "tur", Alpha2Code: "tr", English: "Turkish"},
	{Alpha3bCode: "twi", Alpha2Code: "tw", English: "Twi"},
	{Alpha3bCode: "uig", Alpha2Code: "ug", English: "Uighur; Uyghur"},
	{Alpha3bCode: "ukr", Alpha2Code: "uk", English: "Ukrainian"},
	{Alpha3bCode: "urd", Alpha2Code: "ur", English: "Urdu"},
	{Alpha3bCode: "uzb", Alpha2Code: "uz", English: "Uzbek"},
	{Alpha3bCode: "ven", Alpha2Code: "ve", English: "Venda"},
	{Alpha3bCode: "vie", Alpha2Code: "vi", English: "Vietnamese"},
	{Alpha3bCode: "vol", Alpha2Code: "vo", English: "Volapük"},
	{Alpha3bCode: "wel", Alpha2Code: "cy", English: "Welsh"},
	{Alpha3bCode: "wln", Alpha2Code: "wa", English: "Walloon"},
	{Alpha3bCode: "wol", Alpha2Code: "wo", English: "Wolof"},
	{Alpha3bCode: "xho", Alpha2Code: "xh", English: "Xhosa"},
	{Alpha3bCode: "yid", Alpha2Code: "yi", English: "Yiddish"},
	{Alpha3bCode: "yor", Alpha2Code: "yo", English: "Yoruba"},
	{Alpha3bCode: "zha", Alpha2Code: "za", English: "Zhuang; Chuang"},
	{Alpha3bCode: "zul", Alpha2Code: "zu", English: "Zulu"},
}

// LocaleEntry defines an ISO locale code like: de_DE or en_US or zh-Hans-SG
// [Chinese (Simplified, Singapore)].
type LocaleEntry struct {
	Locale  string
	English string
}

// LocaleList contains all locales and their English names. This variable should
// be a private variable to prevent race conditions caused by inexperienced
// developers modifying a map. Only reading from a fixed sized map is race free.
// If you modify this map during runtime you should go straight to hell.
var LocaleList = map[string]LocaleEntry{
	"af":        {Locale: "af", English: "Afrikaans"},
	"afna":      {Locale: "af-NA", English: "Afrikaans (Namibia)"},
	"afza":      {Locale: "af-ZA", English: "Afrikaans (South Africa)"},
	"agq":       {Locale: "agq", English: "Aghem"},
	"agqcm":     {Locale: "agq-CM", English: "Aghem (Cameroon)"},
	"ak":        {Locale: "ak", English: "Akan"},
	"akgh":      {Locale: "ak-GH", English: "Akan (Ghana)"},
	"am":        {Locale: "am", English: "Amharic"},
	"amet":      {Locale: "am-ET", English: "Amharic (Ethiopia)"},
	"ar":        {Locale: "ar", English: "Arabic"},
	"ar001":     {Locale: "ar-001", English: "Arabic (World)"},
	"arae":      {Locale: "ar-AE", English: "Arabic (United Arab Emirates)"},
	"arbh":      {Locale: "ar-BH", English: "Arabic (Bahrain)"},
	"ardj":      {Locale: "ar-DJ", English: "Arabic (Djibouti)"},
	"ardz":      {Locale: "ar-DZ", English: "Arabic (Algeria)"},
	"areg":      {Locale: "ar-EG", English: "Arabic (Egypt)"},
	"areh":      {Locale: "ar-EH", English: "Arabic (Western Sahara)"},
	"arer":      {Locale: "ar-ER", English: "Arabic (Eritrea)"},
	"aril":      {Locale: "ar-IL", English: "Arabic (Israel)"},
	"ariq":      {Locale: "ar-IQ", English: "Arabic (Iraq)"},
	"arjo":      {Locale: "ar-JO", English: "Arabic (Jordan)"},
	"arkm":      {Locale: "ar-KM", English: "Arabic (Comoros)"},
	"arkw":      {Locale: "ar-KW", English: "Arabic (Kuwait)"},
	"arlb":      {Locale: "ar-LB", English: "Arabic (Lebanon)"},
	"arly":      {Locale: "ar-LY", English: "Arabic (Libya)"},
	"arma":      {Locale: "ar-MA", English: "Arabic (Morocco)"},
	"armr":      {Locale: "ar-MR", English: "Arabic (Mauritania)"},
	"arom":      {Locale: "ar-OM", English: "Arabic (Oman)"},
	"arps":      {Locale: "ar-PS", English: "Arabic (Palestinian Territories)"},
	"arqa":      {Locale: "ar-QA", English: "Arabic (Qatar)"},
	"arsa":      {Locale: "ar-SA", English: "Arabic (Saudi Arabia)"},
	"arsd":      {Locale: "ar-SD", English: "Arabic (Sudan)"},
	"arso":      {Locale: "ar-SO", English: "Arabic (Somalia)"},
	"arss":      {Locale: "ar-SS", English: "Arabic (South Sudan)"},
	"arsy":      {Locale: "ar-SY", English: "Arabic (Syria)"},
	"artd":      {Locale: "ar-TD", English: "Arabic (Chad)"},
	"artn":      {Locale: "ar-TN", English: "Arabic (Tunisia)"},
	"arye":      {Locale: "ar-YE", English: "Arabic (Yemen)"},
	"as":        {Locale: "as", English: "Assamese"},
	"asa":       {Locale: "asa", English: "Asu"},
	"asatz":     {Locale: "asa-TZ", English: "Asu (Tanzania)"},
	"asin":      {Locale: "as-IN", English: "Assamese (India)"},
	"az":        {Locale: "az", English: "Azerbaijani"},
	"azcyrl":    {Locale: "az-Cyrl", English: "Azerbaijani (Cyrillic)"},
	"azcyrlaz":  {Locale: "az-Cyrl-AZ", English: "Azerbaijani (Cyrillic, Azerbaijan)"},
	"azlatn":    {Locale: "az-Latn", English: "Azerbaijani (Latin)"},
	"azlatnaz":  {Locale: "az-Latn-AZ", English: "Azerbaijani (Latin, Azerbaijan)"},
	"bas":       {Locale: "bas", English: "Basaa"},
	"bascm":     {Locale: "bas-CM", English: "Basaa (Cameroon)"},
	"be":        {Locale: "be", English: "Belarusian"},
	"beby":      {Locale: "be-BY", English: "Belarusian (Belarus)"},
	"bem":       {Locale: "bem", English: "Bemba"},
	"bemzm":     {Locale: "bem-ZM", English: "Bemba (Zambia)"},
	"bez":       {Locale: "bez", English: "Bena"},
	"beztz":     {Locale: "bez-TZ", English: "Bena (Tanzania)"},
	"bg":        {Locale: "bg", English: "Bulgarian"},
	"bgbg":      {Locale: "bg-BG", English: "Bulgarian (Bulgaria)"},
	"bm":        {Locale: "bm", English: "Bambara"},
	"bmlatn":    {Locale: "bm-Latn", English: "Bambara (Latin)"},
	"bmlatnml":  {Locale: "bm-Latn-ML", English: "Bambara (Latin, Mali)"},
	"bn":        {Locale: "bn", English: "Bengali"},
	"bnbd":      {Locale: "bn-BD", English: "Bengali (Bangladesh)"},
	"bnin":      {Locale: "bn-IN", English: "Bengali (India)"},
	"bo":        {Locale: "bo", English: "Tibetan"},
	"bocn":      {Locale: "bo-CN", English: "Tibetan (China)"},
	"boin":      {Locale: "bo-IN", English: "Tibetan (India)"},
	"br":        {Locale: "br", English: "Breton"},
	"brfr":      {Locale: "br-FR", English: "Breton (France)"},
	"brx":       {Locale: "brx", English: "Bodo"},
	"brxin":     {Locale: "brx-IN", English: "Bodo (India)"},
	"bs":        {Locale: "bs", English: "Bosnian"},
	"bscyrl":    {Locale: "bs-Cyrl", English: "Bosnian (Cyrillic)"},
	"bscyrlba":  {Locale: "bs-Cyrl-BA", English: "Bosnian (Cyrillic, Bosnia & Herzegovina)"},
	"bslatn":    {Locale: "bs-Latn", English: "Bosnian (Latin)"},
	"bslatnba":  {Locale: "bs-Latn-BA", English: "Bosnian (Latin, Bosnia & Herzegovina)"},
	"ca":        {Locale: "ca", English: "Catalan"},
	"caad":      {Locale: "ca-AD", English: "Catalan (Andorra)"},
	"caes":      {Locale: "ca-ES", English: "Catalan (Spain)"},
	"cafr":      {Locale: "ca-FR", English: "Catalan (France)"},
	"cait":      {Locale: "ca-IT", English: "Catalan (Italy)"},
	"cgg":       {Locale: "cgg", English: "Chiga"},
	"cggug":     {Locale: "cgg-UG", English: "Chiga (Uganda)"},
	"chr":       {Locale: "chr", English: "Cherokee"},
	"chrus":     {Locale: "chr-US", English: "Cherokee (United States)"},
	"ckb":       {Locale: "ckb", English: "Central Kurdish"},
	"ckbiq":     {Locale: "ckb-IQ", English: "Central Kurdish (Iraq)"},
	"ckbir":     {Locale: "ckb-IR", English: "Central Kurdish (Iran)"},
	"cs":        {Locale: "cs", English: "Czech"},
	"cscz":      {Locale: "cs-CZ", English: "Czech (Czech Republic)"},
	"cy":        {Locale: "cy", English: "Welsh"},
	"cygb":      {Locale: "cy-GB", English: "Welsh (United Kingdom)"},
	"da":        {Locale: "da", English: "Danish"},
	"dadk":      {Locale: "da-DK", English: "Danish (Denmark)"},
	"dagl":      {Locale: "da-GL", English: "Danish (Greenland)"},
	"dav":       {Locale: "dav", English: "Taita"},
	"davke":     {Locale: "dav-KE", English: "Taita (Kenya)"},
	"de":        {Locale: "de", English: "German"},
	"deat":      {Locale: "de-AT", English: "German (Austria)"},
	"debe":      {Locale: "de-BE", English: "German (Belgium)"},
	"dech":      {Locale: "de-CH", English: "German (Switzerland)"},
	"dede":      {Locale: "de-DE", English: "German (Germany)"},
	"deli":      {Locale: "de-LI", English: "German (Liechtenstein)"},
	"delu":      {Locale: "de-LU", English: "German (Luxembourg)"},
	"dje":       {Locale: "dje", English: "Zarma"},
	"djene":     {Locale: "dje-NE", English: "Zarma (Niger)"},
	"dsb":       {Locale: "dsb", English: "Lower Sorbian"},
	"dsbde":     {Locale: "dsb-DE", English: "Lower Sorbian (Germany)"},
	"dua":       {Locale: "dua", English: "Duala"},
	"duacm":     {Locale: "dua-CM", English: "Duala (Cameroon)"},
	"dyo":       {Locale: "dyo", English: "Jola-Fonyi"},
	"dyosn":     {Locale: "dyo-SN", English: "Jola-Fonyi (Senegal)"},
	"dz":        {Locale: "dz", English: "Dzongkha"},
	"dzbt":      {Locale: "dz-BT", English: "Dzongkha (Bhutan)"},
	"ebu":       {Locale: "ebu", English: "Embu"},
	"ebuke":     {Locale: "ebu-KE", English: "Embu (Kenya)"},
	"ee":        {Locale: "ee", English: "Ewe"},
	"eegh":      {Locale: "ee-GH", English: "Ewe (Ghana)"},
	"eetg":      {Locale: "ee-TG", English: "Ewe (Togo)"},
	"el":        {Locale: "el", English: "Greek"},
	"elcy":      {Locale: "el-CY", English: "Greek (Cyprus)"},
	"elgr":      {Locale: "el-GR", English: "Greek (Greece)"},
	"en":        {Locale: "en", English: "English"},
	"en001":     {Locale: "en-001", English: "English (World)"},
	"en150":     {Locale: "en-150", English: "English (Europe)"},
	"enad":      {Locale: "en-AD", English: "English (Andorra)"},
	"enag":      {Locale: "en-AG", English: "English (Antigua & Barbuda)"},
	"enai":      {Locale: "en-AI", English: "English (Anguilla)"},
	"enal":      {Locale: "en-AL", English: "English (Albania)"},
	"enas":      {Locale: "en-AS", English: "English (American Samoa)"},
	"enat":      {Locale: "en-AT", English: "English (Austria)"},
	"enau":      {Locale: "en-AU", English: "English (Australia)"},
	"enba":      {Locale: "en-BA", English: "English (Bosnia & Herzegovina)"},
	"enbb":      {Locale: "en-BB", English: "English (Barbados)"},
	"enbe":      {Locale: "en-BE", English: "English (Belgium)"},
	"enbm":      {Locale: "en-BM", English: "English (Bermuda)"},
	"enbs":      {Locale: "en-BS", English: "English (Bahamas)"},
	"enbw":      {Locale: "en-BW", English: "English (Botswana)"},
	"enbz":      {Locale: "en-BZ", English: "English (Belize)"},
	"enca":      {Locale: "en-CA", English: "English (Canada)"},
	"encc":      {Locale: "en-CC", English: "English (Cocos [Keeling] Islands)"},
	"ench":      {Locale: "en-CH", English: "English (Switzerland)"},
	"enck":      {Locale: "en-CK", English: "English (Cook Islands)"},
	"encm":      {Locale: "en-CM", English: "English (Cameroon)"},
	"encx":      {Locale: "en-CX", English: "English (Christmas Island)"},
	"ency":      {Locale: "en-CY", English: "English (Cyprus)"},
	"encz":      {Locale: "en-CZ", English: "English (Czech Republic)"},
	"ende":      {Locale: "en-DE", English: "English (Germany)"},
	"endg":      {Locale: "en-DG", English: "English (Diego Garcia)"},
	"endk":      {Locale: "en-DK", English: "English (Denmark)"},
	"endm":      {Locale: "en-DM", English: "English (Dominica)"},
	"enee":      {Locale: "en-EE", English: "English (Estonia)"},
	"ener":      {Locale: "en-ER", English: "English (Eritrea)"},
	"enes":      {Locale: "en-ES", English: "English (Spain)"},
	"enfi":      {Locale: "en-FI", English: "English (Finland)"},
	"enfj":      {Locale: "en-FJ", English: "English (Fiji)"},
	"enfk":      {Locale: "en-FK", English: "English (Falkland Islands)"},
	"enfm":      {Locale: "en-FM", English: "English (Micronesia)"},
	"enfr":      {Locale: "en-FR", English: "English (France)"},
	"engb":      {Locale: "en-GB", English: "English (United Kingdom)"},
	"engd":      {Locale: "en-GD", English: "English (Grenada)"},
	"engg":      {Locale: "en-GG", English: "English (Guernsey)"},
	"engh":      {Locale: "en-GH", English: "English (Ghana)"},
	"engi":      {Locale: "en-GI", English: "English (Gibraltar)"},
	"engm":      {Locale: "en-GM", English: "English (Gambia)"},
	"engr":      {Locale: "en-GR", English: "English (Greece)"},
	"engu":      {Locale: "en-GU", English: "English (Guam)"},
	"engy":      {Locale: "en-GY", English: "English (Guyana)"},
	"enhk":      {Locale: "en-HK", English: "English (Hong Kong SAR China)"},
	"enhr":      {Locale: "en-HR", English: "English (Croatia)"},
	"enhu":      {Locale: "en-HU", English: "English (Hungary)"},
	"enie":      {Locale: "en-IE", English: "English (Ireland)"},
	"enil":      {Locale: "en-IL", English: "English (Israel)"},
	"enim":      {Locale: "en-IM", English: "English (Isle of Man)"},
	"enin":      {Locale: "en-IN", English: "English (India)"},
	"enio":      {Locale: "en-IO", English: "English (British Indian Ocean Territory)"},
	"enis":      {Locale: "en-IS", English: "English (Iceland)"},
	"enit":      {Locale: "en-IT", English: "English (Italy)"},
	"enje":      {Locale: "en-JE", English: "English (Jersey)"},
	"enjm":      {Locale: "en-JM", English: "English (Jamaica)"},
	"enke":      {Locale: "en-KE", English: "English (Kenya)"},
	"enki":      {Locale: "en-KI", English: "English (Kiribati)"},
	"enkn":      {Locale: "en-KN", English: "English (St. Kitts & Nevis)"},
	"enky":      {Locale: "en-KY", English: "English (Cayman Islands)"},
	"enlc":      {Locale: "en-LC", English: "English (St. Lucia)"},
	"enlr":      {Locale: "en-LR", English: "English (Liberia)"},
	"enls":      {Locale: "en-LS", English: "English (Lesotho)"},
	"enlt":      {Locale: "en-LT", English: "English (Lithuania)"},
	"enlu":      {Locale: "en-LU", English: "English (Luxembourg)"},
	"enlv":      {Locale: "en-LV", English: "English (Latvia)"},
	"enme":      {Locale: "en-ME", English: "English (Montenegro)"},
	"enmg":      {Locale: "en-MG", English: "English (Madagascar)"},
	"enmh":      {Locale: "en-MH", English: "English (Marshall Islands)"},
	"enmo":      {Locale: "en-MO", English: "English (Macau SAR China)"},
	"enmp":      {Locale: "en-MP", English: "English (Northern Mariana Islands)"},
	"enms":      {Locale: "en-MS", English: "English (Montserrat)"},
	"enmt":      {Locale: "en-MT", English: "English (Malta)"},
	"enmu":      {Locale: "en-MU", English: "English (Mauritius)"},
	"enmw":      {Locale: "en-MW", English: "English (Malawi)"},
	"enmy":      {Locale: "en-MY", English: "English (Malaysia)"},
	"enna":      {Locale: "en-NA", English: "English (Namibia)"},
	"ennf":      {Locale: "en-NF", English: "English (Norfolk Island)"},
	"enng":      {Locale: "en-NG", English: "English (Nigeria)"},
	"ennl":      {Locale: "en-NL", English: "English (Netherlands)"},
	"enno":      {Locale: "en-NO", English: "English (Norway)"},
	"ennr":      {Locale: "en-NR", English: "English (Nauru)"},
	"ennu":      {Locale: "en-NU", English: "English (Niue)"},
	"ennz":      {Locale: "en-NZ", English: "English (New Zealand)"},
	"enpg":      {Locale: "en-PG", English: "English (Papua New Guinea)"},
	"enph":      {Locale: "en-PH", English: "English (Philippines)"},
	"enpk":      {Locale: "en-PK", English: "English (Pakistan)"},
	"enpl":      {Locale: "en-PL", English: "English (Poland)"},
	"enpn":      {Locale: "en-PN", English: "English (Pitcairn Islands)"},
	"enpr":      {Locale: "en-PR", English: "English (Puerto Rico)"},
	"enpt":      {Locale: "en-PT", English: "English (Portugal)"},
	"enpw":      {Locale: "en-PW", English: "English (Palau)"},
	"enro":      {Locale: "en-RO", English: "English (Romania)"},
	"enru":      {Locale: "en-RU", English: "English (Russia)"},
	"enrw":      {Locale: "en-RW", English: "English (Rwanda)"},
	"ensb":      {Locale: "en-SB", English: "English (Solomon Islands)"},
	"ensc":      {Locale: "en-SC", English: "English (Seychelles)"},
	"ensd":      {Locale: "en-SD", English: "English (Sudan)"},
	"ense":      {Locale: "en-SE", English: "English (Sweden)"},
	"ensg":      {Locale: "en-SG", English: "English (Singapore)"},
	"ensh":      {Locale: "en-SH", English: "English (St. Helena)"},
	"ensi":      {Locale: "en-SI", English: "English (Slovenia)"},
	"ensk":      {Locale: "en-SK", English: "English (Slovakia)"},
	"ensl":      {Locale: "en-SL", English: "English (Sierra Leone)"},
	"enss":      {Locale: "en-SS", English: "English (South Sudan)"},
	"ensx":      {Locale: "en-SX", English: "English (Sint Maarten)"},
	"ensz":      {Locale: "en-SZ", English: "English (Swaziland)"},
	"entc":      {Locale: "en-TC", English: "English (Turks & Caicos Islands)"},
	"entk":      {Locale: "en-TK", English: "English (Tokelau)"},
	"ento":      {Locale: "en-TO", English: "English (Tonga)"},
	"entr":      {Locale: "en-TR", English: "English (Turkey)"},
	"entt":      {Locale: "en-TT", English: "English (Trinidad & Tobago)"},
	"entv":      {Locale: "en-TV", English: "English (Tuvalu)"},
	"entz":      {Locale: "en-TZ", English: "English (Tanzania)"},
	"enug":      {Locale: "en-UG", English: "English (Uganda)"},
	"enum":      {Locale: "en-UM", English: "English (U.S. Outlying Islands)"},
	"enus":      {Locale: "en-US", English: "English (United States)"},
	"enusposix": {Locale: "en-US-POSIX", English: "English (United States, Computer)"},
	"envc":      {Locale: "en-VC", English: "English (St. Vincent & Grenadines)"},
	"envg":      {Locale: "en-VG", English: "English (British Virgin Islands)"},
	"envi":      {Locale: "en-VI", English: "English (U.S. Virgin Islands)"},
	"envu":      {Locale: "en-VU", English: "English (Vanuatu)"},
	"enws":      {Locale: "en-WS", English: "English (Samoa)"},
	"enza":      {Locale: "en-ZA", English: "English (South Africa)"},
	"enzm":      {Locale: "en-ZM", English: "English (Zambia)"},
	"enzw":      {Locale: "en-ZW", English: "English (Zimbabwe)"},
	"eo":        {Locale: "eo", English: "Esperanto"},
	"es":        {Locale: "es", English: "Spanish"},
	"es419":     {Locale: "es-419", English: "Spanish (Latin America)"},
	"esar":      {Locale: "es-AR", English: "Spanish (Argentina)"},
	"esbo":      {Locale: "es-BO", English: "Spanish (Bolivia)"},
	"escl":      {Locale: "es-CL", English: "Spanish (Chile)"},
	"esco":      {Locale: "es-CO", English: "Spanish (Colombia)"},
	"escr":      {Locale: "es-CR", English: "Spanish (Costa Rica)"},
	"escu":      {Locale: "es-CU", English: "Spanish (Cuba)"},
	"esdo":      {Locale: "es-DO", English: "Spanish (Dominican Republic)"},
	"esea":      {Locale: "es-EA", English: "Spanish (Ceuta & Melilla)"},
	"esec":      {Locale: "es-EC", English: "Spanish (Ecuador)"},
	"eses":      {Locale: "es-ES", English: "Spanish (Spain)"},
	"esgq":      {Locale: "es-GQ", English: "Spanish (Equatorial Guinea)"},
	"esgt":      {Locale: "es-GT", English: "Spanish (Guatemala)"},
	"eshn":      {Locale: "es-HN", English: "Spanish (Honduras)"},
	"esic":      {Locale: "es-IC", English: "Spanish (Canary Islands)"},
	"esmx":      {Locale: "es-MX", English: "Spanish (Mexico)"},
	"esni":      {Locale: "es-NI", English: "Spanish (Nicaragua)"},
	"espa":      {Locale: "es-PA", English: "Spanish (Panama)"},
	"espe":      {Locale: "es-PE", English: "Spanish (Peru)"},
	"esph":      {Locale: "es-PH", English: "Spanish (Philippines)"},
	"espr":      {Locale: "es-PR", English: "Spanish (Puerto Rico)"},
	"espy":      {Locale: "es-PY", English: "Spanish (Paraguay)"},
	"essv":      {Locale: "es-SV", English: "Spanish (El Salvador)"},
	"esus":      {Locale: "es-US", English: "Spanish (United States)"},
	"esuy":      {Locale: "es-UY", English: "Spanish (Uruguay)"},
	"esve":      {Locale: "es-VE", English: "Spanish (Venezuela)"},
	"et":        {Locale: "et", English: "Estonian"},
	"etee":      {Locale: "et-EE", English: "Estonian (Estonia)"},
	"eu":        {Locale: "eu", English: "Basque"},
	"eues":      {Locale: "eu-ES", English: "Basque (Spain)"},
	"ewo":       {Locale: "ewo", English: "Ewondo"},
	"ewocm":     {Locale: "ewo-CM", English: "Ewondo (Cameroon)"},
	"fa":        {Locale: "fa", English: "Persian"},
	"faaf":      {Locale: "fa-AF", English: "Persian (Afghanistan)"},
	"fair":      {Locale: "fa-IR", English: "Persian (Iran)"},
	"ff":        {Locale: "ff", English: "Fulah"},
	"ffcm":      {Locale: "ff-CM", English: "Fulah (Cameroon)"},
	"ffgn":      {Locale: "ff-GN", English: "Fulah (Guinea)"},
	"ffmr":      {Locale: "ff-MR", English: "Fulah (Mauritania)"},
	"ffsn":      {Locale: "ff-SN", English: "Fulah (Senegal)"},
	"fi":        {Locale: "fi", English: "Finnish"},
	"fifi":      {Locale: "fi-FI", English: "Finnish (Finland)"},
	"fil":       {Locale: "fil", English: "Filipino"},
	"filph":     {Locale: "fil-PH", English: "Filipino (Philippines)"},
	"fo":        {Locale: "fo", English: "Faroese"},
	"fofo":      {Locale: "fo-FO", English: "Faroese (Faroe Islands)"},
	"fr":        {Locale: "fr", English: "French"},
	"frbe":      {Locale: "fr-BE", English: "French (Belgium)"},
	"frbf":      {Locale: "fr-BF", English: "French (Burkina Faso)"},
	"frbi":      {Locale: "fr-BI", English: "French (Burundi)"},
	"frbj":      {Locale: "fr-BJ", English: "French (Benin)"},
	"frbl":      {Locale: "fr-BL", English: "French (St. Barthélemy)"},
	"frca":      {Locale: "fr-CA", English: "French (Canada)"},
	"frcd":      {Locale: "fr-CD", English: "French (Congo - Kinshasa)"},
	"frcf":      {Locale: "fr-CF", English: "French (Central African Republic)"},
	"frcg":      {Locale: "fr-CG", English: "French (Congo - Brazzaville)"},
	"frch":      {Locale: "fr-CH", English: "French (Switzerland)"},
	"frci":      {Locale: "fr-CI", English: "French (Côte d’Ivoire)"},
	"frcm":      {Locale: "fr-CM", English: "French (Cameroon)"},
	"frdj":      {Locale: "fr-DJ", English: "French (Djibouti)"},
	"frdz":      {Locale: "fr-DZ", English: "French (Algeria)"},
	"frfr":      {Locale: "fr-FR", English: "French (France)"},
	"frga":      {Locale: "fr-GA", English: "French (Gabon)"},
	"frgf":      {Locale: "fr-GF", English: "French (French Guiana)"},
	"frgn":      {Locale: "fr-GN", English: "French (Guinea)"},
	"frgp":      {Locale: "fr-GP", English: "French (Guadeloupe)"},
	"frgq":      {Locale: "fr-GQ", English: "French (Equatorial Guinea)"},
	"frht":      {Locale: "fr-HT", English: "French (Haiti)"},
	"frkm":      {Locale: "fr-KM", English: "French (Comoros)"},
	"frlu":      {Locale: "fr-LU", English: "French (Luxembourg)"},
	"frma":      {Locale: "fr-MA", English: "French (Morocco)"},
	"frmc":      {Locale: "fr-MC", English: "French (Monaco)"},
	"frmf":      {Locale: "fr-MF", English: "French (St. Martin)"},
	"frmg":      {Locale: "fr-MG", English: "French (Madagascar)"},
	"frml":      {Locale: "fr-ML", English: "French (Mali)"},
	"frmq":      {Locale: "fr-MQ", English: "French (Martinique)"},
	"frmr":      {Locale: "fr-MR", English: "French (Mauritania)"},
	"frmu":      {Locale: "fr-MU", English: "French (Mauritius)"},
	"frnc":      {Locale: "fr-NC", English: "French (New Caledonia)"},
	"frne":      {Locale: "fr-NE", English: "French (Niger)"},
	"frpf":      {Locale: "fr-PF", English: "French (French Polynesia)"},
	"frpm":      {Locale: "fr-PM", English: "French (St. Pierre & Miquelon)"},
	"frre":      {Locale: "fr-RE", English: "French (Réunion)"},
	"frrw":      {Locale: "fr-RW", English: "French (Rwanda)"},
	"frsc":      {Locale: "fr-SC", English: "French (Seychelles)"},
	"frsn":      {Locale: "fr-SN", English: "French (Senegal)"},
	"frsy":      {Locale: "fr-SY", English: "French (Syria)"},
	"frtd":      {Locale: "fr-TD", English: "French (Chad)"},
	"frtg":      {Locale: "fr-TG", English: "French (Togo)"},
	"frtn":      {Locale: "fr-TN", English: "French (Tunisia)"},
	"frvu":      {Locale: "fr-VU", English: "French (Vanuatu)"},
	"frwf":      {Locale: "fr-WF", English: "French (Wallis & Futuna)"},
	"fryt":      {Locale: "fr-YT", English: "French (Mayotte)"},
	"fur":       {Locale: "fur", English: "Friulian"},
	"furit":     {Locale: "fur-IT", English: "Friulian (Italy)"},
	"fy":        {Locale: "fy", English: "Western Frisian"},
	"fynl":      {Locale: "fy-NL", English: "Western Frisian (Netherlands)"},
	"ga":        {Locale: "ga", English: "Irish"},
	"gaie":      {Locale: "ga-IE", English: "Irish (Ireland)"},
	"gd":        {Locale: "gd", English: "Scottish Gaelic"},
	"gdgb":      {Locale: "gd-GB", English: "Scottish Gaelic (United Kingdom)"},
	"gl":        {Locale: "gl", English: "Galician"},
	"gles":      {Locale: "gl-ES", English: "Galician (Spain)"},
	"gsw":       {Locale: "gsw", English: "Swiss German"},
	"gswch":     {Locale: "gsw-CH", English: "Swiss German (Switzerland)"},
	"gswfr":     {Locale: "gsw-FR", English: "Swiss German (France)"},
	"gswli":     {Locale: "gsw-LI", English: "Swiss German (Liechtenstein)"},
	"gu":        {Locale: "gu", English: "Gujarati"},
	"guin":      {Locale: "gu-IN", English: "Gujarati (India)"},
	"guz":       {Locale: "guz", English: "Gusii"},
	"guzke":     {Locale: "guz-KE", English: "Gusii (Kenya)"},
	"gv":        {Locale: "gv", English: "Manx"},
	"gvim":      {Locale: "gv-IM", English: "Manx (Isle of Man)"},
	"ha":        {Locale: "ha", English: "Hausa"},
	"halatn":    {Locale: "ha-Latn", English: "Hausa (Latin)"},
	"halatngh":  {Locale: "ha-Latn-GH", English: "Hausa (Latin, Ghana)"},
	"halatnne":  {Locale: "ha-Latn-NE", English: "Hausa (Latin, Niger)"},
	"halatnng":  {Locale: "ha-Latn-NG", English: "Hausa (Latin, Nigeria)"},
	"haw":       {Locale: "haw", English: "Hawaiian"},
	"hawus":     {Locale: "haw-US", English: "Hawaiian (United States)"},
	"he":        {Locale: "he", English: "Hebrew"},
	"heil":      {Locale: "he-IL", English: "Hebrew (Israel)"},
	"hi":        {Locale: "hi", English: "Hindi"},
	"hiin":      {Locale: "hi-IN", English: "Hindi (India)"},
	"hr":        {Locale: "hr", English: "Croatian"},
	"hrba":      {Locale: "hr-BA", English: "Croatian (Bosnia & Herzegovina)"},
	"hrhr":      {Locale: "hr-HR", English: "Croatian (Croatia)"},
	"hsb":       {Locale: "hsb", English: "Upper Sorbian"},
	"hsbde":     {Locale: "hsb-DE", English: "Upper Sorbian (Germany)"},
	"hu":        {Locale: "hu", English: "Hungarian"},
	"huhu":      {Locale: "hu-HU", English: "Hungarian (Hungary)"},
	"hy":        {Locale: "hy", English: "Armenian"},
	"hyam":      {Locale: "hy-AM", English: "Armenian (Armenia)"},
	"id":        {Locale: "id", English: "Indonesian"},
	"idid":      {Locale: "id-ID", English: "Indonesian (Indonesia)"},
	"ig":        {Locale: "ig", English: "Igbo"},
	"igng":      {Locale: "ig-NG", English: "Igbo (Nigeria)"},
	"ii":        {Locale: "ii", English: "Sichuan Yi"},
	"iicn":      {Locale: "ii-CN", English: "Sichuan Yi (China)"},
	"is":        {Locale: "is", English: "Icelandic"},
	"isis":      {Locale: "is-IS", English: "Icelandic (Iceland)"},
	"it":        {Locale: "it", English: "Italian"},
	"itch":      {Locale: "it-CH", English: "Italian (Switzerland)"},
	"itit":      {Locale: "it-IT", English: "Italian (Italy)"},
	"itsm":      {Locale: "it-SM", English: "Italian (San Marino)"},
	"iu":        {Locale: "iu", English: "Inuktitut"},
	"iucans":    {Locale: "iu-Cans", English: "Inuktitut (Unified Canadian Aboriginal Syllabics)"},
	"iucansca":  {Locale: "iu-Cans-CA", English: "Inuktitut (Unified Canadian Aboriginal Syllabics, Canada)"},
	"ja":        {Locale: "ja", English: "Japanese"},
	"jajp":      {Locale: "ja-JP", English: "Japanese (Japan)"},
	"jgo":       {Locale: "jgo", English: "Ngomba"},
	"jgocm":     {Locale: "jgo-CM", English: "Ngomba (Cameroon)"},
	"jmc":       {Locale: "jmc", English: "Machame"},
	"jmctz":     {Locale: "jmc-TZ", English: "Machame (Tanzania)"},
	"ka":        {Locale: "ka", English: "Georgian"},
	"kab":       {Locale: "kab", English: "Kabyle"},
	"kabdz":     {Locale: "kab-DZ", English: "Kabyle (Algeria)"},
	"kage":      {Locale: "ka-GE", English: "Georgian (Georgia)"},
	"kam":       {Locale: "kam", English: "Kamba"},
	"kamke":     {Locale: "kam-KE", English: "Kamba (Kenya)"},
	"kde":       {Locale: "kde", English: "Makonde"},
	"kdetz":     {Locale: "kde-TZ", English: "Makonde (Tanzania)"},
	"kea":       {Locale: "kea", English: "Kabuverdianu"},
	"keacv":     {Locale: "kea-CV", English: "Kabuverdianu (Cape Verde)"},
	"khq":       {Locale: "khq", English: "Koyra Chiini"},
	"khqml":     {Locale: "khq-ML", English: "Koyra Chiini (Mali)"},
	"ki":        {Locale: "ki", English: "Kikuyu"},
	"kike":      {Locale: "ki-KE", English: "Kikuyu (Kenya)"},
	"kk":        {Locale: "kk", English: "Kazakh"},
	"kkcyrl":    {Locale: "kk-Cyrl", English: "Kazakh (Cyrillic)"},
	"kkcyrlkz":  {Locale: "kk-Cyrl-KZ", English: "Kazakh (Cyrillic, Kazakhstan)"},
	"kkj":       {Locale: "kkj", English: "Kako"},
	"kkjcm":     {Locale: "kkj-CM", English: "Kako (Cameroon)"},
	"kl":        {Locale: "kl", English: "Kalaallisut"},
	"klgl":      {Locale: "kl-GL", English: "Kalaallisut (Greenland)"},
	"kln":       {Locale: "kln", English: "Kalenjin"},
	"klnke":     {Locale: "kln-KE", English: "Kalenjin (Kenya)"},
	"km":        {Locale: "km", English: "Khmer"},
	"kmkh":      {Locale: "km-KH", English: "Khmer (Cambodia)"},
	"kn":        {Locale: "kn", English: "Kannada"},
	"knin":      {Locale: "kn-IN", English: "Kannada (India)"},
	"ko":        {Locale: "ko", English: "Korean"},
	"kok":       {Locale: "kok", English: "Konkani"},
	"kokin":     {Locale: "kok-IN", English: "Konkani (India)"},
	"kokp":      {Locale: "ko-KP", English: "Korean (North Korea)"},
	"kokr":      {Locale: "ko-KR", English: "Korean (South Korea)"},
	"ks":        {Locale: "ks", English: "Kashmiri"},
	"ksarab":    {Locale: "ks-Arab", English: "Kashmiri (Arabic)"},
	"ksarabin":  {Locale: "ks-Arab-IN", English: "Kashmiri (Arabic, India)"},
	"ksb":       {Locale: "ksb", English: "Shambala"},
	"ksbtz":     {Locale: "ksb-TZ", English: "Shambala (Tanzania)"},
	"ksf":       {Locale: "ksf", English: "Bafia"},
	"ksfcm":     {Locale: "ksf-CM", English: "Bafia (Cameroon)"},
	"ksh":       {Locale: "ksh", English: "Colognian"},
	"kshde":     {Locale: "ksh-DE", English: "Colognian (Germany)"},
	"kw":        {Locale: "kw", English: "Cornish"},
	"kwgb":      {Locale: "kw-GB", English: "Cornish (United Kingdom)"},
	"ky":        {Locale: "ky", English: "Kyrgyz"},
	"kycyrl":    {Locale: "ky-Cyrl", English: "Kyrgyz (Cyrillic)"},
	"kycyrlkg":  {Locale: "ky-Cyrl-KG", English: "Kyrgyz (Cyrillic, Kyrgyzstan)"},
	"lag":       {Locale: "lag", English: "Langi"},
	"lagtz":     {Locale: "lag-TZ", English: "Langi (Tanzania)"},
	"lb":        {Locale: "lb", English: "Luxembourgish"},
	"lblu":      {Locale: "lb-LU", English: "Luxembourgish (Luxembourg)"},
	"lg":        {Locale: "lg", English: "Ganda"},
	"lgug":      {Locale: "lg-UG", English: "Ganda (Uganda)"},
	"lkt":       {Locale: "lkt", English: "Lakota"},
	"lktus":     {Locale: "lkt-US", English: "Lakota (United States)"},
	"ln":        {Locale: "ln", English: "Lingala"},
	"lnao":      {Locale: "ln-AO", English: "Lingala (Angola)"},
	"lncd":      {Locale: "ln-CD", English: "Lingala (Congo - Kinshasa)"},
	"lncf":      {Locale: "ln-CF", English: "Lingala (Central African Republic)"},
	"lncg":      {Locale: "ln-CG", English: "Lingala (Congo - Brazzaville)"},
	"lo":        {Locale: "lo", English: "Lao"},
	"lola":      {Locale: "lo-LA", English: "Lao (Laos)"},
	"lt":        {Locale: "lt", English: "Lithuanian"},
	"ltlt":      {Locale: "lt-LT", English: "Lithuanian (Lithuania)"},
	"lu":        {Locale: "lu", English: "Luba-Katanga"},
	"lucd":      {Locale: "lu-CD", English: "Luba-Katanga (Congo - Kinshasa)"},
	"luo":       {Locale: "luo", English: "Luo"},
	"luoke":     {Locale: "luo-KE", English: "Luo (Kenya)"},
	"luy":       {Locale: "luy", English: "Luyia"},
	"luyke":     {Locale: "luy-KE", English: "Luyia (Kenya)"},
	"lv":        {Locale: "lv", English: "Latvian"},
	"lvlv":      {Locale: "lv-LV", English: "Latvian (Latvia)"},
	"mas":       {Locale: "mas", English: "Masai"},
	"maske":     {Locale: "mas-KE", English: "Masai (Kenya)"},
	"mastz":     {Locale: "mas-TZ", English: "Masai (Tanzania)"},
	"mer":       {Locale: "mer", English: "Meru"},
	"merke":     {Locale: "mer-KE", English: "Meru (Kenya)"},
	"mfe":       {Locale: "mfe", English: "Morisyen"},
	"mfemu":     {Locale: "mfe-MU", English: "Morisyen (Mauritius)"},
	"mg":        {Locale: "mg", English: "Malagasy"},
	"mgh":       {Locale: "mgh", English: "Makhuwa-Meetto"},
	"mghmz":     {Locale: "mgh-MZ", English: "Makhuwa-Meetto (Mozambique)"},
	"mgmg":      {Locale: "mg-MG", English: "Malagasy (Madagascar)"},
	"mgo":       {Locale: "mgo", English: "Metaʼ"},
	"mgocm":     {Locale: "mgo-CM", English: "Metaʼ (Cameroon)"},
	"mk":        {Locale: "mk", English: "Macedonian"},
	"mkmk":      {Locale: "mk-MK", English: "Macedonian (Macedonia)"},
	"ml":        {Locale: "ml", English: "Malayalam"},
	"mlin":      {Locale: "ml-IN", English: "Malayalam (India)"},
	"mn":        {Locale: "mn", English: "Mongolian"},
	"mncyrl":    {Locale: "mn-Cyrl", English: "Mongolian (Cyrillic)"},
	"mncyrlmn":  {Locale: "mn-Cyrl-MN", English: "Mongolian (Cyrillic, Mongolia)"},
	"mr":        {Locale: "mr", English: "Marathi"},
	"mrin":      {Locale: "mr-IN", English: "Marathi (India)"},
	"ms":        {Locale: "ms", English: "Malay"},
	"msarab":    {Locale: "ms-Arab", English: "Malay (Arabic)"},
	"msarabbn":  {Locale: "ms-Arab-BN", English: "Malay (Arabic, Brunei)"},
	"msarabmy":  {Locale: "ms-Arab-MY", English: "Malay (Arabic, Malaysia)"},
	"mslatn":    {Locale: "ms-Latn", English: "Malay (Latin)"},
	"mslatnbn":  {Locale: "ms-Latn-BN", English: "Malay (Latin, Brunei)"},
	"mslatnmy":  {Locale: "ms-Latn-MY", English: "Malay (Latin, Malaysia)"},
	"mslatnsg":  {Locale: "ms-Latn-SG", English: "Malay (Latin, Singapore)"},
	"mt":        {Locale: "mt", English: "Maltese"},
	"mtmt":      {Locale: "mt-MT", English: "Maltese (Malta)"},
	"mua":       {Locale: "mua", English: "Mundang"},
	"muacm":     {Locale: "mua-CM", English: "Mundang (Cameroon)"},
	"my":        {Locale: "my", English: "Burmese"},
	"mymm":      {Locale: "my-MM", English: "Burmese (Myanmar [Burma])"},
	"naq":       {Locale: "naq", English: "Nama"},
	"naqna":     {Locale: "naq-NA", English: "Nama (Namibia)"},
	"nb":        {Locale: "nb", English: "Norwegian Bokmål"},
	"nbno":      {Locale: "nb-NO", English: "Norwegian Bokmål (Norway)"},
	"nbsj":      {Locale: "nb-SJ", English: "Norwegian Bokmål (Svalbard & Jan Mayen)"},
	"nd":        {Locale: "nd", English: "North Ndebele"},
	"ndzw":      {Locale: "nd-ZW", English: "North Ndebele (Zimbabwe)"},
	"ne":        {Locale: "ne", English: "Nepali"},
	"nein":      {Locale: "ne-IN", English: "Nepali (India)"},
	"nenp":      {Locale: "ne-NP", English: "Nepali (Nepal)"},
	"nl":        {Locale: "nl", English: "Dutch"},
	"nlaw":      {Locale: "nl-AW", English: "Dutch (Aruba)"},
	"nlbe":      {Locale: "nl-BE", English: "Dutch (Belgium)"},
	"nlbq":      {Locale: "nl-BQ", English: "Dutch (Caribbean Netherlands)"},
	"nlcw":      {Locale: "nl-CW", English: "Dutch (Curaçao)"},
	"nlnl":      {Locale: "nl-NL", English: "Dutch (Netherlands)"},
	"nlsr":      {Locale: "nl-SR", English: "Dutch (Suriname)"},
	"nlsx":      {Locale: "nl-SX", English: "Dutch (Sint Maarten)"},
	"nmg":       {Locale: "nmg", English: "Kwasio"},
	"nmgcm":     {Locale: "nmg-CM", English: "Kwasio (Cameroon)"},
	"nn":        {Locale: "nn", English: "Norwegian Nynorsk"},
	"nnh":       {Locale: "nnh", English: "Ngiemboon"},
	"nnhcm":     {Locale: "nnh-CM", English: "Ngiemboon (Cameroon)"},
	"nnno":      {Locale: "nn-NO", English: "Norwegian Nynorsk (Norway)"},
	"nus":       {Locale: "nus", English: "Nuer"},
	"nussd":     {Locale: "nus-SD", English: "Nuer (Sudan)"},
	"nyn":       {Locale: "nyn", English: "Nyankole"},
	"nynug":     {Locale: "nyn-UG", English: "Nyankole (Uganda)"},
	"om":        {Locale: "om", English: "Oromo"},
	"omet":      {Locale: "om-ET", English: "Oromo (Ethiopia)"},
	"omke":      {Locale: "om-KE", English: "Oromo (Kenya)"},
	"or":        {Locale: "or", English: "Oriya"},
	"orin":      {Locale: "or-IN", English: "Oriya (India)"},
	"os":        {Locale: "os", English: "Ossetic"},
	"osge":      {Locale: "os-GE", English: "Ossetic (Georgia)"},
	"osru":      {Locale: "os-RU", English: "Ossetic (Russia)"},
	"pa":        {Locale: "pa", English: "Punjabi"},
	"paarab":    {Locale: "pa-Arab", English: "Punjabi (Arabic)"},
	"paarabpk":  {Locale: "pa-Arab-PK", English: "Punjabi (Arabic, Pakistan)"},
	"paguru":    {Locale: "pa-Guru", English: "Punjabi (Gurmukhi)"},
	"paguruin":  {Locale: "pa-Guru-IN", English: "Punjabi (Gurmukhi, India)"},
	"pl":        {Locale: "pl", English: "Polish"},
	"plpl":      {Locale: "pl-PL", English: "Polish (Poland)"},
	"ps":        {Locale: "ps", English: "Pashto"},
	"psaf":      {Locale: "ps-AF", English: "Pashto (Afghanistan)"},
	"pt":        {Locale: "pt", English: "Portuguese"},
	"ptao":      {Locale: "pt-AO", English: "Portuguese (Angola)"},
	"ptbr":      {Locale: "pt-BR", English: "Portuguese (Brazil)"},
	"ptcv":      {Locale: "pt-CV", English: "Portuguese (Cape Verde)"},
	"ptgw":      {Locale: "pt-GW", English: "Portuguese (Guinea-Bissau)"},
	"ptmo":      {Locale: "pt-MO", English: "Portuguese (Macau SAR China)"},
	"ptmz":      {Locale: "pt-MZ", English: "Portuguese (Mozambique)"},
	"ptpt":      {Locale: "pt-PT", English: "Portuguese (Portugal)"},
	"ptst":      {Locale: "pt-ST", English: "Portuguese (São Tomé & Príncipe)"},
	"pttl":      {Locale: "pt-TL", English: "Portuguese (Timor-Leste)"},
	"qu":        {Locale: "qu", English: "Quechua"},
	"qubo":      {Locale: "qu-BO", English: "Quechua (Bolivia)"},
	"quec":      {Locale: "qu-EC", English: "Quechua (Ecuador)"},
	"qupe":      {Locale: "qu-PE", English: "Quechua (Peru)"},
	"rm":        {Locale: "rm", English: "Romansh"},
	"rmch":      {Locale: "rm-CH", English: "Romansh (Switzerland)"},
	"rn":        {Locale: "rn", English: "Rundi"},
	"rnbi":      {Locale: "rn-BI", English: "Rundi (Burundi)"},
	"ro":        {Locale: "ro", English: "Romanian"},
	"rof":       {Locale: "rof", English: "Rombo"},
	"roftz":     {Locale: "rof-TZ", English: "Rombo (Tanzania)"},
	"romd":      {Locale: "ro-MD", English: "Romanian (Moldova)"},
	"roro":      {Locale: "ro-RO", English: "Romanian (Romania)"},
	"ru":        {Locale: "ru", English: "Russian"},
	"ruby":      {Locale: "ru-BY", English: "Russian (Belarus)"},
	"rukg":      {Locale: "ru-KG", English: "Russian (Kyrgyzstan)"},
	"rukz":      {Locale: "ru-KZ", English: "Russian (Kazakhstan)"},
	"rumd":      {Locale: "ru-MD", English: "Russian (Moldova)"},
	"ruru":      {Locale: "ru-RU", English: "Russian (Russia)"},
	"ruua":      {Locale: "ru-UA", English: "Russian (Ukraine)"},
	"rw":        {Locale: "rw", English: "Kinyarwanda"},
	"rwk":       {Locale: "rwk", English: "Rwa"},
	"rwktz":     {Locale: "rwk-TZ", English: "Rwa (Tanzania)"},
	"rwrw":      {Locale: "rw-RW", English: "Kinyarwanda (Rwanda)"},
	"sah":       {Locale: "sah", English: "Sakha"},
	"sahru":     {Locale: "sah-RU", English: "Sakha (Russia)"},
	"saq":       {Locale: "saq", English: "Samburu"},
	"saqke":     {Locale: "saq-KE", English: "Samburu (Kenya)"},
	"sbp":       {Locale: "sbp", English: "Sangu"},
	"sbptz":     {Locale: "sbp-TZ", English: "Sangu (Tanzania)"},
	"se":        {Locale: "se", English: "Northern Sami"},
	"sefi":      {Locale: "se-FI", English: "Northern Sami (Finland)"},
	"seh":       {Locale: "seh", English: "Sena"},
	"sehmz":     {Locale: "seh-MZ", English: "Sena (Mozambique)"},
	"seno":      {Locale: "se-NO", English: "Northern Sami (Norway)"},
	"ses":       {Locale: "ses", English: "Koyraboro Senni"},
	"sese":      {Locale: "se-SE", English: "Northern Sami (Sweden)"},
	"sesml":     {Locale: "ses-ML", English: "Koyraboro Senni (Mali)"},
	"sg":        {Locale: "sg", English: "Sango"},
	"sgcf":      {Locale: "sg-CF", English: "Sango (Central African Republic)"},
	"shi":       {Locale: "shi", English: "Tachelhit"},
	"shilatn":   {Locale: "shi-Latn", English: "Tachelhit (Latin)"},
	"shilatnma": {Locale: "shi-Latn-MA", English: "Tachelhit (Latin, Morocco)"},
	"shitfng":   {Locale: "shi-Tfng", English: "Tachelhit (Tifinagh)"},
	"shitfngma": {Locale: "shi-Tfng-MA", English: "Tachelhit (Tifinagh, Morocco)"},
	"si":        {Locale: "si", English: "Sinhala"},
	"silk":      {Locale: "si-LK", English: "Sinhala (Sri Lanka)"},
	"sk":        {Locale: "sk", English: "Slovak"},
	"sksk":      {Locale: "sk-SK", English: "Slovak (Slovakia)"},
	"sl":        {Locale: "sl", English: "Slovenian"},
	"slsi":      {Locale: "sl-SI", English: "Slovenian (Slovenia)"},
	"smn":       {Locale: "smn", English: "Inari Sami"},
	"smnfi":     {Locale: "smn-FI", English: "Inari Sami (Finland)"},
	"sn":        {Locale: "sn", English: "Shona"},
	"snzw":      {Locale: "sn-ZW", English: "Shona (Zimbabwe)"},
	"so":        {Locale: "so", English: "Somali"},
	"sodj":      {Locale: "so-DJ", English: "Somali (Djibouti)"},
	"soet":      {Locale: "so-ET", English: "Somali (Ethiopia)"},
	"soke":      {Locale: "so-KE", English: "Somali (Kenya)"},
	"soso":      {Locale: "so-SO", English: "Somali (Somalia)"},
	"sq":        {Locale: "sq", English: "Albanian"},
	"sqal":      {Locale: "sq-AL", English: "Albanian (Albania)"},
	"sqmk":      {Locale: "sq-MK", English: "Albanian (Macedonia)"},
	"sqxk":      {Locale: "sq-XK", English: "Albanian (Kosovo)"},
	"sr":        {Locale: "sr", English: "Serbian"},
	"srcyrl":    {Locale: "sr-Cyrl", English: "Serbian (Cyrillic)"},
	"srcyrlba":  {Locale: "sr-Cyrl-BA", English: "Serbian (Cyrillic, Bosnia & Herzegovina)"},
	"srcyrlme":  {Locale: "sr-Cyrl-ME", English: "Serbian (Cyrillic, Montenegro)"},
	"srcyrlrs":  {Locale: "sr-Cyrl-RS", English: "Serbian (Cyrillic, Serbia)"},
	"srcyrlxk":  {Locale: "sr-Cyrl-XK", English: "Serbian (Cyrillic, Kosovo)"},
	"srlatn":    {Locale: "sr-Latn", English: "Serbian (Latin)"},
	"srlatnba":  {Locale: "sr-Latn-BA", English: "Serbian (Latin, Bosnia & Herzegovina)"},
	"srlatnme":  {Locale: "sr-Latn-ME", English: "Serbian (Latin, Montenegro)"},
	"srlatnrs":  {Locale: "sr-Latn-RS", English: "Serbian (Latin, Serbia)"},
	"srlatnxk":  {Locale: "sr-Latn-XK", English: "Serbian (Latin, Kosovo)"},
	"sv":        {Locale: "sv", English: "Swedish"},
	"svax":      {Locale: "sv-AX", English: "Swedish (Åland Islands)"},
	"svfi":      {Locale: "sv-FI", English: "Swedish (Finland)"},
	"svse":      {Locale: "sv-SE", English: "Swedish (Sweden)"},
	"sw":        {Locale: "sw", English: "Swahili"},
	"swcd":      {Locale: "sw-CD", English: "Swahili (Congo - Kinshasa)"},
	"swke":      {Locale: "sw-KE", English: "Swahili (Kenya)"},
	"swtz":      {Locale: "sw-TZ", English: "Swahili (Tanzania)"},
	"swug":      {Locale: "sw-UG", English: "Swahili (Uganda)"},
	"ta":        {Locale: "ta", English: "Tamil"},
	"tain":      {Locale: "ta-IN", English: "Tamil (India)"},
	"talk":      {Locale: "ta-LK", English: "Tamil (Sri Lanka)"},
	"tamy":      {Locale: "ta-MY", English: "Tamil (Malaysia)"},
	"tasg":      {Locale: "ta-SG", English: "Tamil (Singapore)"},
	"te":        {Locale: "te", English: "Telugu"},
	"tein":      {Locale: "te-IN", English: "Telugu (India)"},
	"teo":       {Locale: "teo", English: "Teso"},
	"teoke":     {Locale: "teo-KE", English: "Teso (Kenya)"},
	"teoug":     {Locale: "teo-UG", English: "Teso (Uganda)"},
	"tg":        {Locale: "tg", English: "Tajik"},
	"tgcyrl":    {Locale: "tg-Cyrl", English: "Tajik (Cyrillic)"},
	"tgcyrltj":  {Locale: "tg-Cyrl-TJ", English: "Tajik (Cyrillic, Tajikistan)"},
	"th":        {Locale: "th", English: "Thai"},
	"thth":      {Locale: "th-TH", English: "Thai (Thailand)"},
	"ti":        {Locale: "ti", English: "Tigrinya"},
	"tier":      {Locale: "ti-ER", English: "Tigrinya (Eritrea)"},
	"tiet":      {Locale: "ti-ET", English: "Tigrinya (Ethiopia)"},
	"tk":        {Locale: "tk", English: "Turkmen"},
	"tklatn":    {Locale: "tk-Latn", English: "Turkmen (Latin)"},
	"tklatntm":  {Locale: "tk-Latn-TM", English: "Turkmen (Latin, Turkmenistan)"},
	"to":        {Locale: "to", English: "Tongan"},
	"toto":      {Locale: "to-TO", English: "Tongan (Tonga)"},
	"tr":        {Locale: "tr", English: "Turkish"},
	"trcy":      {Locale: "tr-CY", English: "Turkish (Cyprus)"},
	"trtr":      {Locale: "tr-TR", English: "Turkish (Turkey)"},
	"twq":       {Locale: "twq", English: "Tasawaq"},
	"twqne":     {Locale: "twq-NE", English: "Tasawaq (Niger)"},
	"tzm":       {Locale: "tzm", English: "Central Atlas Tamazight"},
	"tzmlatn":   {Locale: "tzm-Latn", English: "Central Atlas Tamazight (Latin)"},
	"tzmlatnma": {Locale: "tzm-Latn-MA", English: "Central Atlas Tamazight (Latin, Morocco)"},
	"ug":        {Locale: "ug", English: "Uyghur"},
	"ugarab":    {Locale: "ug-Arab", English: "Uyghur (Arabic)"},
	"ugarabcn":  {Locale: "ug-Arab-CN", English: "Uyghur (Arabic, China)"},
	"uk":        {Locale: "uk", English: "Ukrainian"},
	"ukua":      {Locale: "uk-UA", English: "Ukrainian (Ukraine)"},
	"ur":        {Locale: "ur", English: "Urdu"},
	"urin":      {Locale: "ur-IN", English: "Urdu (India)"},
	"urpk":      {Locale: "ur-PK", English: "Urdu (Pakistan)"},
	"uz":        {Locale: "uz", English: "Uzbek"},
	"uzarab":    {Locale: "uz-Arab", English: "Uzbek (Arabic)"},
	"uzarabaf":  {Locale: "uz-Arab-AF", English: "Uzbek (Arabic, Afghanistan)"},
	"uzcyrl":    {Locale: "uz-Cyrl", English: "Uzbek (Cyrillic)"},
	"uzcyrluz":  {Locale: "uz-Cyrl-UZ", English: "Uzbek (Cyrillic, Uzbekistan)"},
	"uzlatn":    {Locale: "uz-Latn", English: "Uzbek (Latin)"},
	"uzlatnuz":  {Locale: "uz-Latn-UZ", English: "Uzbek (Latin, Uzbekistan)"},
	"vai":       {Locale: "vai", English: "Vai"},
	"vailatn":   {Locale: "vai-Latn", English: "Vai (Latin)"},
	"vailatnlr": {Locale: "vai-Latn-LR", English: "Vai (Latin, Liberia)"},
	"vaivaii":   {Locale: "vai-Vaii", English: "Vai (Vai)"},
	"vaivaiilr": {Locale: "vai-Vaii-LR", English: "Vai (Vai, Liberia)"},
	"vi":        {Locale: "vi", English: "Vietnamese"},
	"vivn":      {Locale: "vi-VN", English: "Vietnamese (Vietnam)"},
	"vun":       {Locale: "vun", English: "Vunjo"},
	"vuntz":     {Locale: "vun-TZ", English: "Vunjo (Tanzania)"},
	"wae":       {Locale: "wae", English: "Walser"},
	"waech":     {Locale: "wae-CH", English: "Walser (Switzerland)"},
	"xog":       {Locale: "xog", English: "Soga"},
	"xogug":     {Locale: "xog-UG", English: "Soga (Uganda)"},
	"yav":       {Locale: "yav", English: "Yangben"},
	"yavcm":     {Locale: "yav-CM", English: "Yangben (Cameroon)"},
	"yi":        {Locale: "yi", English: "Yiddish"},
	"yi001":     {Locale: "yi-001", English: "Yiddish (World)"},
	"yo":        {Locale: "yo", English: "Yoruba"},
	"yobj":      {Locale: "yo-BJ", English: "Yoruba (Benin)"},
	"yong":      {Locale: "yo-NG", English: "Yoruba (Nigeria)"},
	"zgh":       {Locale: "zgh", English: "Standard Moroccan Tamazight"},
	"zghma":     {Locale: "zgh-MA", English: "Standard Moroccan Tamazight (Morocco)"},
	"zh":        {Locale: "zh", English: "Chinese"},
	"zhhans":    {Locale: "zh-Hans", English: "Chinese (Simplified)"},
	"zhhanscn":  {Locale: "zh-Hans-CN", English: "Chinese (Simplified, China)"},
	"zhhanshk":  {Locale: "zh-Hans-HK", English: "Chinese (Simplified, Hong Kong SAR China)"},
	"zhhansmo":  {Locale: "zh-Hans-MO", English: "Chinese (Simplified, Macau SAR China)"},
	"zhhanssg":  {Locale: "zh-Hans-SG", English: "Chinese (Simplified, Singapore)"},
	"zhhant":    {Locale: "zh-Hant", English: "Chinese (Traditional)"},
	"zhhanthk":  {Locale: "zh-Hant-HK", English: "Chinese (Traditional, Hong Kong SAR China)"},
	"zhhantmo":  {Locale: "zh-Hant-MO", English: "Chinese (Traditional, Macau SAR China)"},
	"zhhanttw":  {Locale: "zh-Hant-TW", English: "Chinese (Traditional, Taiwan)"},
	"zu":        {Locale: "zu", English: "Zulu"},
	"zuza":      {Locale: "zu-ZA", English: "Zulu (South Africa)"},
}
