// +build ignore

package salesrule

import (
	"github.com/corestoreio/csfw/config/element"
	"github.com/corestoreio/csfw/config/model"
)

// Backend will be initialized in the init() function together with ConfigStructure.
var Backend *PkgBackend

// PkgBackend just exported for the sake of documentation. See fields
// for more information. The PkgBackend handles the reading and writing
// of configuration values within this package.
type PkgBackend struct {
	model.PkgBackend
	// PromoAutoGeneratedCouponCodesLength => Code Length.
	// Excluding prefix, suffix and separators.
	// Path: promo/auto_generated_coupon_codes/length
	PromoAutoGeneratedCouponCodesLength model.Str

	// PromoAutoGeneratedCouponCodesFormat => Code Format.
	// Path: promo/auto_generated_coupon_codes/format
	// SourceModel: Otnegam\SalesRule\Model\System\Config\Source\Coupon\Format
	PromoAutoGeneratedCouponCodesFormat model.Str

	// PromoAutoGeneratedCouponCodesPrefix => Code Prefix.
	// Path: promo/auto_generated_coupon_codes/prefix
	PromoAutoGeneratedCouponCodesPrefix model.Str

	// PromoAutoGeneratedCouponCodesSuffix => Code Suffix.
	// Path: promo/auto_generated_coupon_codes/suffix
	PromoAutoGeneratedCouponCodesSuffix model.Str

	// PromoAutoGeneratedCouponCodesDash => Dash Every X Characters.
	// If empty no separation.
	// Path: promo/auto_generated_coupon_codes/dash
	PromoAutoGeneratedCouponCodesDash model.Str

	// RssCatalogDiscounts => Coupons/Discounts.
	// Path: rss/catalog/discounts
	// SourceModel: Otnegam\Config\Model\Config\Source\Enabledisable
	RssCatalogDiscounts model.Bool
}

// NewBackend initializes the global Backend variable. See init()
func NewBackend(cfgStruct element.SectionSlice) *PkgBackend {
	return (&PkgBackend{}).init(cfgStruct)
}

func (pp *PkgBackend) init(cfgStruct element.SectionSlice) *PkgBackend {
	pp.Lock()
	defer pp.Unlock()
	pp.PromoAutoGeneratedCouponCodesLength = model.NewStr(`promo/auto_generated_coupon_codes/length`, model.WithConfigStructure(cfgStruct))
	pp.PromoAutoGeneratedCouponCodesFormat = model.NewStr(`promo/auto_generated_coupon_codes/format`, model.WithConfigStructure(cfgStruct))
	pp.PromoAutoGeneratedCouponCodesPrefix = model.NewStr(`promo/auto_generated_coupon_codes/prefix`, model.WithConfigStructure(cfgStruct))
	pp.PromoAutoGeneratedCouponCodesSuffix = model.NewStr(`promo/auto_generated_coupon_codes/suffix`, model.WithConfigStructure(cfgStruct))
	pp.PromoAutoGeneratedCouponCodesDash = model.NewStr(`promo/auto_generated_coupon_codes/dash`, model.WithConfigStructure(cfgStruct))
	pp.RssCatalogDiscounts = model.NewBool(`rss/catalog/discounts`, model.WithConfigStructure(cfgStruct))

	return pp
}
