// +build ignore

package salesrule

import (
	"github.com/corestoreio/csfw/config/element"
	"github.com/corestoreio/csfw/config/model"
)

// Path will be initialized in the init() function together with PackageConfiguration.
var Path *PkgPath

// PkgPath global configuration struct containing paths and how to retrieve
// their values and options.
type PkgPath struct {
	model.PkgPath
	// PromoAutoGeneratedCouponCodesLength => Code Length.
	// Excluding prefix, suffix and separators.
	// Path: promo/auto_generated_coupon_codes/length
	PromoAutoGeneratedCouponCodesLength model.Str

	// PromoAutoGeneratedCouponCodesFormat => Code Format.
	// Path: promo/auto_generated_coupon_codes/format
	// SourceModel: Otnegam\SalesRule\Model\System\Config\Source\Coupon\Format
	PromoAutoGeneratedCouponCodesFormat model.Str

	// PromoAutoGeneratedCouponCodesPrefix => Code Prefix.
	// Path: promo/auto_generated_coupon_codes/prefix
	PromoAutoGeneratedCouponCodesPrefix model.Str

	// PromoAutoGeneratedCouponCodesSuffix => Code Suffix.
	// Path: promo/auto_generated_coupon_codes/suffix
	PromoAutoGeneratedCouponCodesSuffix model.Str

	// PromoAutoGeneratedCouponCodesDash => Dash Every X Characters.
	// If empty no separation.
	// Path: promo/auto_generated_coupon_codes/dash
	PromoAutoGeneratedCouponCodesDash model.Str

	// RssCatalogDiscounts => Coupons/Discounts.
	// Path: rss/catalog/discounts
	// SourceModel: Otnegam\Config\Model\Config\Source\Enabledisable
	RssCatalogDiscounts model.Bool
}

// NewPath initializes the global Path variable. See init()
func NewPath(pkgCfg element.SectionSlice) *PkgPath {
	return (&PkgPath{}).init(pkgCfg)
}

func (pp *PkgPath) init(pkgCfg element.SectionSlice) *PkgPath {
	pp.Lock()
	defer pp.Unlock()
	pp.PromoAutoGeneratedCouponCodesLength = model.NewStr(`promo/auto_generated_coupon_codes/length`, model.WithPkgCfg(pkgCfg))
	pp.PromoAutoGeneratedCouponCodesFormat = model.NewStr(`promo/auto_generated_coupon_codes/format`, model.WithPkgCfg(pkgCfg))
	pp.PromoAutoGeneratedCouponCodesPrefix = model.NewStr(`promo/auto_generated_coupon_codes/prefix`, model.WithPkgCfg(pkgCfg))
	pp.PromoAutoGeneratedCouponCodesSuffix = model.NewStr(`promo/auto_generated_coupon_codes/suffix`, model.WithPkgCfg(pkgCfg))
	pp.PromoAutoGeneratedCouponCodesDash = model.NewStr(`promo/auto_generated_coupon_codes/dash`, model.WithPkgCfg(pkgCfg))
	pp.RssCatalogDiscounts = model.NewBool(`rss/catalog/discounts`, model.WithPkgCfg(pkgCfg))

	return pp
}
