// +build  csall json proto

// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package observer

import (
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
)

func easyjson32fe820fDecodeGithubComCorestoreioPkgConfigObserver(in *jlexer.Lexer, out *ModifierArg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "funcs":
			if in.IsNull() {
				in.Skip()
				out.Funcs = nil
			} else {
				in.Delim('[')
				if out.Funcs == nil {
					if !in.IsDelim(']') {
						out.Funcs = make([]string, 0, 4)
					} else {
						out.Funcs = []string{}
					}
				} else {
					out.Funcs = (out.Funcs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Funcs = append(out.Funcs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson32fe820fEncodeGithubComCorestoreioPkgConfigObserver(out *jwriter.Writer, in ModifierArg) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Funcs) != 0 {
		const prefix string = ",\"funcs\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v2, v3 := range in.Funcs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ModifierArg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson32fe820fEncodeGithubComCorestoreioPkgConfigObserver(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ModifierArg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson32fe820fEncodeGithubComCorestoreioPkgConfigObserver(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ModifierArg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson32fe820fDecodeGithubComCorestoreioPkgConfigObserver(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ModifierArg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson32fe820fDecodeGithubComCorestoreioPkgConfigObserver(l, v)
}
